import type { CharacterDef } from '../types';

/**
 * Prototype Character pool. Ability text is the source of truth for players;
 * the `effect` objects are what the engine executes.
 */
export const CHARACTERS: CharacterDef[] = [
  {
    kind: 'character',
    id: 'harriet_tubman',
    name: 'Harriet Tubman',
    short: 'Harriet',
    influence: 3,
    force: 2,
    tags: ['Black', 'Abolition'],
    keywords: [],
    reveal: {
      text: "Move one friendly Gate Character to another Location's open Gate. Its waiting progress is preserved.",
      effect: { type: 'moveFriendlyGate' },
      needsTarget: 'friendlyGateCharAndLocation',
    },
    established: {
      text: "The first friendly Character relocated into Harriet's Location each turn becomes Ready immediately.",
      effect: { type: 'readyRelocatedIn' },
    },
    identity: ['freedom', 'movement', 'rescue', 'strategy'],
    era: '1822–1913',
    blurb: 'Conductor of the Underground Railroad who returned again and again to bring people out.',
  },
  {
    kind: 'character',
    id: 'frederick_douglass',
    name: 'Frederick Douglass',
    short: 'Douglass',
    influence: 4,
    force: 1,
    tags: ['Black', 'Abolition', 'Orator'],
    keywords: [],
    reveal: {
      text: 'Another friendly Character here gains +1 Influence this turn.',
      effect: { type: 'tempInfluenceOther', amount: 1 },
    },
    established: {
      text: 'Your other Characters here gain +1 Influence.',
      effect: { type: 'auraInfluenceOthersHere', amount: 1 },
    },
    identity: ['communication', 'leadership', 'persuasion', 'organizing'],
    era: '1818–1895',
    blurb: 'Escaped slavery and became the most photographed American of the 19th century through the power of his words.',
  },
  {
    kind: 'character',
    id: 'john_brown',
    name: 'John Brown',
    short: 'J. Brown',
    influence: 2,
    force: 5,
    tags: ['Ally', 'Abolition'],
    keywords: [],
    reveal: {
      text: 'Confront one neutral Threat here with +2 Force.',
      effect: { type: 'confrontThreat', bonus: 2 },
    },
    established: {
      text: 'When assisting against a Threat, John Brown contributes +1 additional Force.',
      effect: { type: 'assistForceBonus', amount: 1 },
    },
    identity: ['abolition', 'confrontation', 'sacrifice', 'ally'],
    era: '1800–1859',
    blurb: 'Abolitionist who led the raid on Harpers Ferry in 1859, convinced that slavery would not end without force.',
  },
  {
    kind: 'character',
    id: 'katherine_johnson',
    name: 'Katherine Johnson',
    short: 'Katherine',
    influence: 3,
    force: 2,
    tags: ['Black', 'Science'],
    keywords: [],
    reveal: {
      text: 'If any Locations remain hidden, privately learn which Location will reveal next.',
      effect: { type: 'peekNextReveal' },
    },
    established: {
      text: 'Characters you relocate cannot be displaced the turn they arrive.',
      effect: { type: 'relocatedNoDisplace' },
    },
    identity: ['calculation', 'foresight', 'precision'],
    era: '1918–2020',
    blurb: 'NASA mathematician whose trajectory calculations put John Glenn in orbit and Apollo 11 on the Moon.',
  },
  {
    kind: 'character',
    id: 'mansa_musa',
    name: 'Mansa Musa',
    short: 'Mansa Musa',
    influence: 5,
    force: 3,
    tags: ['Black', 'Mali', 'Ruler'],
    keywords: [],
    reveal: {
      text: 'If played into a hidden Location, gain +1 Influence when that Location reveals.',
      effect: { type: 'hiddenBonus', amount: 1 },
    },
    established: {
      text: 'The next Character you Establish here gains +1 Influence while Mansa Musa remains here.',
      effect: { type: 'blessNextEstablished', amount: 1 },
    },
    identity: ['scale', 'prosperity', 'establishment', 'prestige'],
    era: 'c. 1280–1337',
    blurb: 'Emperor of Mali whose pilgrimage to Mecca spent so much gold it depressed prices across the Mediterranean.',
  },
  {
    kind: 'character',
    id: 'zora_neale_hurston',
    name: 'Zora Neale Hurston',
    short: 'Zora',
    influence: 3,
    force: 1,
    tags: ['Black', 'Writer', 'Harlem Renaissance'],
    keywords: [],
    reveal: {
      text: 'Draw a card.',
      effect: { type: 'draw', count: 1 },
    },
    established: {
      text: 'Your Gate Characters here gain +1 Influence.',
      effect: { type: 'gateInfluenceHere', amount: 1 },
    },
    identity: ['story', 'folklore', 'anthropology', 'voice'],
    era: '1891–1960',
    blurb: 'Novelist and anthropologist who recorded the folklore of the rural South and wrote Their Eyes Were Watching God.',
  },
  {
    kind: 'character',
    id: 'karen',
    name: 'Karen',
    short: 'Karen',
    influence: 1,
    force: 1,
    tags: ['Archetype', 'Disruption'],
    keywords: [],
    reveal: {
      text: 'The opposing Ready Gate Character here with the highest Influence cannot enter this turn. Then Karen becomes unstable.',
      effect: { type: 'blockOneOpposingGate' },
    },
    passive: {
      text: 'While present, the leading player at her Location loses 1 Influence. At the end of each turn she may relocate to a random Location.',
      unstable: true,
      leaderPenalty: 1,
    },
    identity: ['entitlement', 'disruption', 'unreliability'],
    era: 'Timeless',
    blurb: 'An archetype, not a person. Useful for a turn, then a liability for whoever is winning.',
  },
  {
    kind: 'character',
    id: 'pullman_porter',
    name: 'Pullman Porter',
    short: 'Porter',
    influence: 2,
    force: 2,
    tags: ['Black', 'Archetype', 'Labor'],
    keywords: ['DIRECT_ENTRY'],
    established: {
      text: 'You may make one additional Relocation each turn.',
      effect: { type: 'extraRelocation', amount: 1 },
    },
    identity: ['mobility', 'network', 'labor', 'news'],
    era: '1867–1968',
    blurb: 'Porters rode every line in the country, carrying the Chicago Defender and the news of the Great Migration with them.',
  },
  {
    kind: 'character',
    id: 'organizer',
    name: 'Organizer',
    short: 'Organizer',
    influence: 2,
    force: 2,
    tags: ['Black', 'Archetype', 'Movement'],
    keywords: [],
    reveal: {
      text: 'Another friendly Fresh Gate Character (here if possible) becomes Ready.',
      effect: { type: 'readyFriendly' },
    },
    established: {
      text: 'You may play one additional card each turn.',
      effect: { type: 'extraPlay', amount: 1 },
    },
    identity: ['mobilization', 'community', 'tempo'],
    era: 'Timeless',
    blurb: 'The person with the clipboard, the church basement and the phone tree.',
  },
  {
    kind: 'character',
    id: 'og',
    name: 'OG',
    short: 'OG',
    influence: 3,
    force: 3,
    tags: ['Black', 'Archetype', 'Community'],
    keywords: [],
    reveal: {
      text: 'Opposing Gate Characters here cannot enter this turn.',
      effect: { type: 'blockOpposingGatesHere' },
    },
    established: {
      text: 'Opposing Gate Characters here contribute 1 less Influence.',
      effect: { type: 'opposingGateInfluence', amount: 1 },
    },
    identity: ['respect', 'territory', 'gatekeeping'],
    era: 'Timeless',
    blurb: 'Everybody on the block knows who you talk to first.',
  },
  {
    kind: 'character',
    id: 'ida_b_wells',
    name: 'Ida B. Wells',
    short: 'Ida',
    influence: 4,
    force: 1,
    tags: ['Black', 'Journalist', 'Anti-lynching'],
    keywords: [],
    reveal: {
      text: 'EXPOSE: a Threat here permanently needs 2 less Force to neutralize.',
      effect: { type: 'weakenThreat', amount: 2 },
    },
    established: {
      text: 'Whenever a Threat at this Location is neutralized, Ida gains +2 Influence.',
      effect: { type: 'influenceOnThreatCleared', amount: 2 },
    },
    identity: ['exposure', 'press', 'courage', 'record'],
    era: '1862–1931',
    blurb: 'Investigative journalist who documented lynching with names, dates and evidence when no one else would print them.',
  },
  {
    kind: 'character',
    id: 'queen_nzinga',
    name: 'Queen Nzinga',
    short: 'Nzinga',
    influence: 3,
    force: 4,
    tags: ['Black', 'Ndongo', 'Ruler', 'Military'],
    keywords: [],
    reveal: {
      text: "CHALLENGE the opposing Gate Character here with the highest Force. If Nzinga's Force is higher, DISPLACE it to a random other Location's Gate.",
      effect: { type: 'challengeGate' },
    },
    established: {
      text: 'Your Characters here gain +1 Force.',
      effect: { type: 'forceAuraHere', amount: 1 },
    },
    identity: ['resistance', 'diplomacy', 'warfare', 'sovereignty'],
    era: 'c. 1583–1663',
    blurb: 'Queen of Ndongo and Matamba who fought and negotiated against Portuguese colonization for decades.',
  },
  {
    kind: 'character',
    id: 'toussaint_louverture',
    name: 'Toussaint Louverture',
    short: 'Toussaint',
    influence: 4,
    force: 4,
    tags: ['Black', 'Haiti', 'Revolution', 'Military'],
    keywords: [],
    reveal: {
      text: "CHALLENGE the opposing Established Character here with the highest Influence. If Toussaint's Force is higher, it returns to its Gate, Fresh.",
      effect: { type: 'challengeInside' },
    },
    established: {
      text: 'Your Characters here cannot be displaced.',
      effect: { type: 'noDisplaceHere' },
    },
    identity: ['revolution', 'discipline', 'liberation', 'statecraft'],
    era: '1743–1803',
    blurb: 'Leader of the Haitian Revolution, the only slave revolt in history to found an independent state.',
  },
  {
    kind: 'character',
    id: 'marcus_garvey',
    name: 'Marcus Garvey',
    short: 'Garvey',
    influence: 4,
    force: 2,
    tags: ['Black', 'Pan-African', 'Movement'],
    keywords: [],
    reveal: {
      text: 'Each other friendly Character here gains +1 Influence this turn.',
      effect: { type: 'tempInfluenceAllOthersHere', amount: 1 },
    },
    established: {
      text: 'Characters you relocate out of this Location arrive Ready.',
      effect: { type: 'relocatedOutReady' },
    },
    identity: ['mass movement', 'pride', 'enterprise', 'diaspora'],
    era: '1887–1940',
    blurb: 'Founded the UNIA and the Black Star Line, building the largest mass movement in Black history.',
  },
  {
    kind: 'character',
    id: 'bessie_coleman',
    name: 'Bessie Coleman',
    short: 'Bessie',
    influence: 2,
    force: 3,
    tags: ['Black', 'Aviator'],
    keywords: ['DIRECT_ENTRY'],
    established: {
      text: 'Your Characters here cannot be blocked from entering.',
      effect: { type: 'noBlockHere' },
    },
    identity: ['flight', 'barrier-breaking', 'daring'],
    era: '1892–1926',
    blurb: 'Refused entry to every American flight school, she learned French, trained in Paris and came home a licensed pilot.',
  },
  {
    kind: 'character',
    id: 'sojourner_truth',
    name: 'Sojourner Truth',
    short: 'Sojourner',
    influence: 3,
    force: 2,
    tags: ['Black', 'Abolition', 'Suffrage'],
    keywords: [],
    reveal: {
      text: 'SUPPRESS the opposing Established Character here with the highest Influence until the end of next turn.',
      effect: { type: 'suppressInside' },
    },
    established: {
      text: 'Your Characters here cannot be Suppressed.',
      effect: { type: 'noSuppressHere' },
    },
    identity: ['truth', 'testimony', 'faith', 'defiance'],
    era: 'c. 1797–1883',
    blurb: 'Walked away from slavery, sued a white man for her son and won, and spoke truth that silenced rooms.',
  },
];

CHARACTERS.push({
  kind: 'character',
  id: 'victor_hugo_green',
  name: 'Victor Hugo Green',
  short: 'V. H. Green',
  influence: 3,
  force: 1,
  tags: ['Black', 'Travel', 'Publisher'],
  keywords: [],
  reveal: {
    text: 'Draw a card.',
    effect: { type: 'draw', count: 1 },
  },
  established: {
    text: 'Characters you relocate out of this Location arrive Inside their destination (Established), not at the Gates.',
    effect: { type: 'relocatedOutInside' },
  },
  identity: ['safe passage', 'knowledge', 'network', 'interior to interior'],
  era: '1892–1960',
  blurb: 'Publisher of the Green Book, the guide that told Black travelers where they could eat, sleep and buy gas without danger, including how to get through sundown towns.',
});

export const CHARACTER_BY_ID: Record<string, CharacterDef> = Object.fromEntries(CHARACTERS.map((c) => [c.id, c]));
