import type { CharacterDef } from '../types';

/**
 * Prototype Character pool. Ability text is the source of truth for players;
 * the `effect` objects are what the engine executes.
 */
export const CHARACTERS: CharacterDef[] = [
  {
    kind: 'character',
    id: 'harriet_tubman',
    cost: 2,
    category: 'historical',
    name: 'Harriet Tubman',
    short: 'Harriet',
    influence: 3,
    force: 2,
    tags: ['Black', 'Abolition'],
    keywords: [],
    reveal: {
      text: "Move one friendly Gate Character to another Location's open Gate. It stays as Ready as it was, moves before anyone enters, and does not use your Relocation.",
      effect: { type: 'moveFriendlyGate' },
      needsTarget: 'friendlyGateCharAndLocation',
    },
    established: {
      text: "The first friendly Character relocated into Harriet's Location each turn becomes Ready immediately.",
      effect: { type: 'readyRelocatedIn' },
    },
    identity: ['freedom', 'movement', 'rescue', 'strategy'],
    era: '1822–1913',
    blurb: 'Conductor of the Underground Railroad who returned again and again to bring people out.',
    history: 'Born Araminta Ross into slavery in Dorchester County, Maryland, around 1822, Harriet Tubman escaped in 1849 and then returned to the South roughly thirteen times, guiding about seventy people to freedom on the Underground Railroad and never losing a passenger. During the Civil War she worked for the Union Army as a nurse, scout and spy, and in June 1863 she guided the Combahee River Raid that freed more than seven hundred people, the first woman to lead an armed assault in the war. She spent her later years in Auburn, New York, campaigning for women\'s suffrage and running a home for the elderly.',
  },
  {
    kind: 'character',
    id: 'frederick_douglass',
    cost: 3,
    category: 'historical',
    name: 'Frederick Douglass',
    short: 'Douglass',
    influence: 4,
    force: 1,
    tags: ['Black', 'Abolition', 'Orator'],
    keywords: [],
    reveal: {
      text: 'Another friendly Character here gains +1 Influence this turn.',
      effect: { type: 'tempInfluenceOther', amount: 1 },
    },
    established: {
      text: 'Your other Characters here gain +1 Influence.',
      effect: { type: 'auraInfluenceOthersHere', amount: 1 },
    },
    identity: ['communication', 'leadership', 'persuasion', 'organizing'],
    era: '1818–1895',
    blurb: 'Escaped slavery and became the most photographed American of the 19th century through the power of his words.',
    history: 'Born enslaved on Maryland\'s Eastern Shore in 1818, Frederick Douglass taught himself to read, escaped to New York in 1838 and became the most famous Black man in the nineteenth-century world. His 1845 Narrative sold tens of thousands of copies, he edited the abolitionist paper The North Star, advised Lincoln on the recruitment of Black soldiers, and later served as U.S. Marshal for the District of Columbia and Minister to Haiti. He sat for more photographs than any other American of his century, because he believed the image of a dignified Black man was itself an argument.',
  },
  {
    kind: 'character',
    id: 'john_brown',
    cost: 2,
    category: 'historical',
    name: 'John Brown',
    short: 'J. Brown',
    influence: 2,
    force: 5,
    tags: ['Ally', 'Abolition'],
    keywords: [],
    reveal: {
      text: 'Confront one neutral Threat here with +2 Force.',
      effect: { type: 'confrontThreat', bonus: 2 },
    },
    established: {
      text: 'When assisting against a Threat, John Brown contributes +1 additional Force.',
      effect: { type: 'assistForceBonus', amount: 1 },
    },
    identity: ['abolition', 'confrontation', 'sacrifice', 'ally'],
    era: '1800–1859',
    blurb: 'Abolitionist who led the raid on Harpers Ferry in 1859, convinced that slavery would not end without force.',
    history: 'A white abolitionist from Connecticut, John Brown believed slavery could only be ended by force. After fighting pro-slavery settlers in Kansas, he led twenty-one men, five of them Black, in a raid on the federal armory at Harpers Ferry, Virginia, on 16 October 1859, hoping to arm an uprising. The raid failed within two days; Brown was tried for treason and hanged on 2 December 1859. His trial speeches and death made him a martyr in the North, and Union soldiers marched to \'John Brown\'s Body\' eighteen months later.',
  },
  {
    kind: 'character',
    id: 'katherine_johnson',
    cost: 2,
    category: 'historical',
    name: 'Katherine Johnson',
    short: 'Katherine',
    influence: 3,
    force: 2,
    tags: ['Black', 'Science'],
    keywords: [],
    reveal: {
      text: 'Launch window: your Characters at this Gate become Ready.',
      effect: { type: 'readyFriendly' },
    },
    established: {
      text: 'Characters you relocate cannot be displaced the turn they arrive.',
      effect: { type: 'relocatedNoDisplace' },
    },
    identity: ['calculation', 'foresight', 'precision'],
    era: '1918–2020',
    blurb: 'NASA mathematician whose trajectory calculations put John Glenn in orbit and Apollo 11 on the Moon.',
    history: 'Katherine Johnson (1918–2020) was a mathematician at NACA and then NASA\'s Langley Research Center. She calculated the trajectory for Alan Shepard\'s 1961 flight, and in 1962 John Glenn asked that she personally re-check the electronic computer\'s figures before his orbital flight. Her work contributed to Apollo 11 and the Space Shuttle. She received the Presidential Medal of Freedom in 2015, and her story reached a wide audience through Hidden Figures.',
  },
  {
    kind: 'character',
    id: 'mansa_musa',
    cost: 4,
    category: 'historical',
    name: 'Mansa Musa',
    short: 'Mansa Musa',
    influence: 5,
    force: 3,
    tags: ['Black', 'Mali', 'Ruler'],
    keywords: [],
    reveal: {
      text: 'If played into a hidden Location, gain +1 Influence when that Location reveals.',
      effect: { type: 'hiddenBonus', amount: 1 },
    },
    established: {
      text: 'The next Character you Establish here gains +1 Influence while Mansa Musa remains here.',
      effect: { type: 'blessNextEstablished', amount: 1 },
    },
    passive: {
      text: 'Gold of Mali: +1 Influence at African Locations (Lagos, Accra).',
      regionBonus: { region: 'africa', influence: 1 },
    },
    identity: ['scale', 'prosperity', 'establishment', 'prestige'],
    era: 'c. 1280–1337',
    blurb: 'Emperor of Mali whose pilgrimage to Mecca spent so much gold it depressed prices across the Mediterranean.',
    history: 'Mansa Musa ruled the Mali Empire from about 1312 to 1337, at the height of its control over the West African gold and salt trade. His 1324 pilgrimage to Mecca, with a caravan reported at tens of thousands of people, spent so much gold in Cairo that the metal\'s value there dropped for years. He returned with scholars and architects, built mosques and madrasas in Timbuktu and Gao, and made Timbuktu a centre of Islamic learning. European maps of the era show him holding a gold nugget.',
  },
  {
    kind: 'character',
    id: 'zora_neale_hurston',
    cost: 2,
    category: 'historical',
    name: 'Zora Neale Hurston',
    short: 'Zora',
    influence: 3,
    force: 1,
    tags: ['Black', 'Writer', 'Harlem Renaissance'],
    keywords: [],
    reveal: {
      text: 'Draw a card.',
      effect: { type: 'draw', count: 1 },
    },
    established: {
      text: 'Your Gate Characters here gain +1 Influence.',
      effect: { type: 'gateInfluenceHere', amount: 1 },
    },
    identity: ['story', 'folklore', 'anthropology', 'voice'],
    era: '1891–1960',
    blurb: 'Novelist and anthropologist who recorded the folklore of the rural South and wrote Their Eyes Were Watching God.',
    history: 'Zora Neale Hurston (1891–1960) grew up in Eatonville, Florida, one of the first all-Black incorporated towns in the country. Trained in anthropology under Franz Boas at Barnard, she collected folklore across the rural South and the Caribbean and published it in Mules and Men. Her 1937 novel Their Eyes Were Watching God was dismissed by some contemporaries and rediscovered decades later, largely through Alice Walker, and is now a cornerstone of American literature.',
  },
  {
    kind: 'character',
    id: 'newsboy',
    cost: 1,
    identity: ['press', 'hustle', 'news'],
    era: '1905–1960',
    category: 'archetype',
    name: 'Newsboy',
    short: 'Newsboy',
    influence: 1,
    force: 1,
    tags: ['Black', 'Archetype', 'Press'],
    keywords: [],
    reveal: {
      text: 'Extra, extra: draw a card.',
      effect: { type: 'draw', count: 1 },
    },
    blurb: 'The Chicago Defender rode south in the bags of Pullman porters and the hands of kids on corners; a paper was the first thing many families bought.',
  },
  {
    kind: 'character',
    id: 'barber',
    cost: 1,
    identity: ['business', 'community', 'talk'],
    era: 'Any Saturday',
    category: 'archetype',
    name: 'Barber',
    short: 'Barber',
    influence: 1,
    force: 2,
    tags: ['Black', 'Archetype', 'Business'],
    keywords: [],
    established: {
      text: 'In and out: Relocations out of this Location do not count against your Relocation limit.',
      effect: { type: 'freeDeparture' },
    },
    blurb: 'The barbershop was bank, newsroom, campaign office and town hall. Everybody passed through, and nobody stayed long.',
  },
  {
    kind: 'character',
    id: 'block_captain',
    cost: 1,
    identity: ['organizing', 'watch', 'neighbors'],
    era: '1960s–',
    category: 'archetype',
    name: 'Block Captain',
    short: 'Captain',
    influence: 1,
    force: 3,
    tags: ['Black', 'Archetype', 'Organizing'],
    keywords: [],
    established: {
      text: 'Your Characters here confront Threats with +1 Force.',
      effect: { type: 'confrontForceHere', amount: 1 },
    },
    blurb: 'Knows every door on the street and who is behind it. When trouble comes, the block already has a plan.',
  },
  {
    kind: 'character',
    id: 'richard_allen',
    cost: 2,
    identity: ['founding', 'independence', 'the pulpit', 'organizing'],
    era: '1760–1831',
    category: 'historical',
    name: 'Richard Allen',
    short: 'Allen',
    influence: 3,
    force: 1,
    tags: ['Black', 'Faith', 'Founder'],
    keywords: [],
    established: {
      text: 'The pulpit: your other Characters here gain +1 Influence.',
      effect: { type: 'auraInfluenceOthersHere', amount: 1 },
    },
    blurb: 'Bought his own freedom, walked out of a segregated church and built his own denomination.',
    history: 'Richard Allen was born enslaved in Philadelphia in 1760, bought his freedom in his twenties and became a Methodist preacher. In 1787, after Black worshippers were pulled from their knees at St. George\'s Church, he and Absalom Jones founded the Free African Society, and in 1794 Allen opened Mother Bethel. In 1816 he brought several Black congregations together as the African Methodist Episcopal Church, the first independent Black denomination in the United States, and became its first bishop. Mother Bethel still stands on the oldest parcel of land continuously owned by Black Americans.',
  },
  {
    kind: 'character',
    id: 'absalom_jones',
    cost: 1,
    identity: ['priesthood', 'patience', 'the open door'],
    era: '1746–1818',
    category: 'historical',
    name: 'Absalom Jones',
    short: 'Jones',
    influence: 1,
    force: 2,
    tags: ['Black', 'Faith', 'Founder'],
    keywords: [],
    established: {
      text: 'The doors are open: your Characters arriving at this Gate are Ready at the end of the turn.',
      effect: { type: 'freshReadyHere' },
    },
    blurb: 'Bought his wife\'s freedom before his own. First Black priest in the Episcopal Church.',
    history: 'Absalom Jones was born enslaved in Delaware in 1746 and taught himself to read from the New Testament. He bought his wife\'s freedom first, so their children would be born free, and his own in 1784. With Richard Allen he founded the Free African Society in 1787, the first Black mutual-aid society in the country, and led the African Church of St. Thomas in Philadelphia, becoming the first Black priest ordained in the Episcopal Church in 1804. During the yellow fever epidemic of 1793 he and Allen organized Black nurses and grave diggers for a city that had fled.',
  },
  {
    kind: 'character',
    id: 'daniel_payne',
    cost: 1,
    identity: ['education', 'discipline', 'the schoolhouse'],
    era: '1811–1893',
    category: 'historical',
    name: 'Daniel Payne',
    short: 'Payne',
    influence: 1,
    force: 1,
    tags: ['Black', 'Faith', 'Education'],
    keywords: [],
    reveal: {
      text: 'Schoolmaster: draw a card.',
      effect: { type: 'draw', count: 1 },
    },
    established: {
      text: 'Wilberforce: gains +1 Influence while another of your Characters is at this Location.',
      effect: { type: 'allyBonus', amount: 1 },
    },
    blurb: 'Ran a school for Black children in Charleston until the state outlawed it. Later ran a university.',
    history: 'Daniel Alexander Payne was born free in Charleston in 1811 and opened a school for Black children at nineteen. South Carolina closed it by law in 1835, and he left for the North, was ordained in the AME Church and became a bishop in 1852. In 1863 he purchased Wilberforce University for the church and served as its president, the first Black president of a college in the United States. He spent decades pushing an educated ministry on a church that did not always want one.',
  },
  {
    kind: 'character',
    id: 'henry_mcneal_turner',
    cost: 2,
    identity: ['chaplaincy', 'politics', 'emigration', 'defiance'],
    era: '1834–1915',
    category: 'historical',
    name: 'Henry McNeal Turner',
    short: 'Turner',
    influence: 2,
    force: 3,
    tags: ['Black', 'Faith', 'Politics'],
    keywords: [],
    established: {
      text: 'Chaplain: your Characters here confront Threats with +1 Force.',
      effect: { type: 'confrontForceHere', amount: 1 },
    },
    passive: {
      text: 'Back to Africa: +2 Influence at The Black Star, +1 Influence anywhere in Africa.',
      locationBonus: { locationId: 'black_star', influence: 2 },
      regionBonus: { region: 'africa', influence: 1 },
    },
    blurb: 'Army chaplain, Georgia legislator expelled for being Black, AME bishop who told his people to leave.',
    history: 'Henry McNeal Turner was born free in South Carolina in 1834, became an AME minister and in 1863 was commissioned the first Black chaplain in the United States Army. Elected to the Georgia legislature in 1868, he was expelled with the other Black members and delivered a speech, "I Am Here to Demand My Rights," that is still read. As an AME bishop he built the church in Georgia and Africa, declared that God is Black, and after the 1890s argued that Black Americans should emigrate, chartering ships to Liberia. He died in Windsor, Ontario, in 1915.',
  },
  {
    kind: 'character',
    id: 'denmark_vesey',
    cost: 3,
    identity: ['freedom', 'organizing', 'secrecy', 'the church'],
    era: 'c. 1767–1822',
    category: 'historical',
    name: 'Denmark Vesey',
    short: 'Vesey',
    influence: 3,
    force: 4,
    tags: ['Black', 'Rebellion', 'Faith'],
    keywords: [],
    reveal: {
      text: 'Challenge the opposing Gate Character here with the highest Influence. Force decides.',
      effect: { type: 'challengeGate' },
    },
    established: {
      text: 'The plan: you have +1 Energy each turn.',
      effect: { type: 'extraEnergy', amount: 1 },
    },
    blurb: 'Won a lottery, bought his freedom, built a church and planned an uprising. Hanged with 34 others.',
    history: 'Denmark Vesey was bought as a boy by a Bermuda slave captain, won $1,500 in a Charleston lottery in 1799 and purchased his own freedom, though not his family\'s. A carpenter and a founder of the city\'s AME church, he organized what would have been one of the largest slave uprisings in American history for the summer of 1822. It was betrayed before it began. Vesey and 34 others were hanged, the church was razed, and the state built a citadel to guard against the next attempt. The church rebuilt as Mother Emanuel.',
  },
  {
    kind: 'character',
    id: 'nat_turner',
    cost: 2,
    identity: ['prophecy', 'rebellion', 'reckoning'],
    era: '1800–1831',
    category: 'historical',
    name: 'Nat Turner',
    short: 'Nat Turner',
    influence: 2,
    force: 4,
    tags: ['Black', 'Rebellion', 'Faith'],
    keywords: [],
    reveal: {
      text: 'Challenge the opposing Established Character here with the highest Influence. Force decides.',
      effect: { type: 'challengeInside' },
    },
    blurb: 'Preacher who saw signs in the sky. Two days in Southampton County in 1831 changed every law in the South.',
    history: 'Nat Turner was born enslaved in Southampton County, Virginia, in 1800, taught to read as a child and known among the enslaved as a preacher who fasted, prayed and saw visions. On 21 August 1831 he led about seventy men across the county, killing around sixty white people in two days before militia scattered them. He hid for two months, was tried and hanged on 11 November, and Virginia and its neighbors answered with new laws against Black literacy, assembly and preaching. His jailhouse account, taken down by a white lawyer, is the only record in something like his own words.',
  },
  {
    kind: 'character',
    id: 'robert_smalls',
    cost: 2,
    identity: ['piloting', 'nerve', 'politics'],
    era: '1839–1915',
    category: 'historical',
    name: 'Robert Smalls',
    short: 'Smalls',
    influence: 3,
    force: 2,
    tags: ['Black', 'Sea', 'Politics'],
    keywords: [],
    reveal: {
      text: 'The Planter: move one of your Gate Characters to another Location\'s Gates for free.',
      effect: { type: 'moveFriendlyGate' },
      needsTarget: 'friendlyGateCharAndLocation',
    },
    established: {
      text: 'Characters who relocate out of this Location arrive Ready.',
      effect: { type: 'relocatedOutReady' },
    },
    blurb: 'Steered a Confederate steamer out of Charleston harbor with his family aboard and handed it to the Union.',
    history: 'Robert Smalls was born enslaved in Beaufort, South Carolina, in 1839 and worked the Charleston waterfront as a pilot. Before dawn on 13 May 1862, with the white officers ashore, he took the armed steamer Planter past five Confederate forts, giving the correct signals at each, picked up his wife and children and surrendered the ship to the Union blockade. He piloted for the Navy, served in the South Carolina legislature and five terms in Congress, wrote the state\'s first public school law, and bought the Beaufort house of the family that had owned him.',
  },
  {
    kind: 'character',
    id: 'madam_cj_walker',
    cost: 3,
    identity: ['enterprise', 'agents', 'philanthropy'],
    era: '1867–1919',
    category: 'historical',
    name: 'Madam C.J. Walker',
    short: 'Walker',
    influence: 4,
    force: 1,
    tags: ['Black', 'Business'],
    keywords: [],
    reveal: {
      text: 'Agents: draw a card.',
      effect: { type: 'draw', count: 1 },
    },
    established: {
      text: 'The next Character you Establish here gains +1 Influence.',
      effect: { type: 'blessNextEstablished', amount: 1 },
    },
    blurb: 'Orphaned laundress who built a hair-care company, thousands of sales agents and the first self-made fortune by an American woman.',
    history: 'Sarah Breedlove was born on a Louisiana plantation in 1867, orphaned at seven, married at fourteen and widowed at twenty. Working as a laundress in St. Louis, she developed a line of hair-care products, renamed herself Madam C.J. Walker and built a company with a factory in Indianapolis and thousands of trained sales agents. By her death in 1919 she was reckoned the first self-made woman millionaire in the country. She funded the NAACP\'s anti-lynching campaign, the Tuskegee Institute and scholarships, and told her agents that their first duty was to their communities.',
  },
  {
    kind: 'character',
    id: 'paul_laurence_dunbar',
    cost: 1,
    identity: ['poetry', 'the mask', 'foresight'],
    era: '1872–1906',
    category: 'historical',
    name: 'Paul Laurence Dunbar',
    short: 'Dunbar',
    influence: 2,
    force: 1,
    tags: ['Black', 'Letters'],
    keywords: [],
    reveal: {
      text: 'If any Locations remain hidden, privately learn which Location will reveal next.',
      effect: { type: 'peekNextReveal' },
    },
    blurb: 'The first Black poet with a national audience. "We Wear the Mask." Dead of tuberculosis at 33.',
    history: 'Paul Laurence Dunbar was born in Dayton, Ohio, in 1872 to parents who had been enslaved in Kentucky. The only Black student in his high school class, he edited the school paper and ran an elevator to pay for printing his first book. Majors and Minors and Lyrics of Lowly Life made him famous by 25; he wrote novels, songs for the Broadway show Clorindy and the poems "Sympathy" and "We Wear the Mask." He died of tuberculosis in 1906, at 33.',
  },
  {
    kind: 'character',
    id: 'scott_joplin',
    cost: 2,
    identity: ['ragtime', 'composition', 'ambition'],
    era: '1868–1917',
    category: 'historical',
    name: 'Scott Joplin',
    short: 'Joplin',
    influence: 2,
    force: 1,
    tags: ['Black', 'Music'],
    keywords: [],
    established: {
      text: 'Ragtime: your Characters at this Gate gain +1 Influence.',
      effect: { type: 'gateInfluenceHere', amount: 1 },
    },
    blurb: 'The King of Ragtime. "Maple Leaf Rag" sold a million copies; his opera waited sixty years for a stage.',
    history: 'Scott Joplin was born in Texas around 1868, the son of a formerly enslaved railroad laborer, and learned piano from a German teacher in Texarkana. In Sedalia, Missouri, he published "Maple Leaf Rag" in 1899, the first sheet music by a Black composer to sell in the hundreds of thousands, and wrote some forty rags that turned a saloon style into a composed art. He spent his last years in New York trying to stage his opera Treemonisha and died in 1917. Treemonisha was finally produced in 1972 and won him a Pulitzer in 1976.',
  },
  {
    kind: 'character',
    id: 'claudette_colvin',
    cost: 1,
    identity: ['courage', 'refusal', 'youth', 'justice'],
    era: '1939–',
    category: 'historical',
    name: 'Claudette Colvin',
    short: 'Claudette',
    influence: 2,
    force: 1,
    tags: ['Black', 'Civil Rights'],
    keywords: [],
    reveal: {
      text: 'Keeps her seat: she cannot be displaced this turn.',
      effect: { type: 'holdSeat' },
    },
    blurb: 'Fifteen years old, Montgomery, March 1955. Nine months before Rosa Parks, she refused to move and was dragged off the bus.',
    history: 'On 2 March 1955, fifteen-year-old Claudette Colvin refused to give up her seat on a segregated Montgomery bus and was arrested, nine months before Rosa Parks. Movement leaders passed her over as the public face of the boycott, but she became one of the four plaintiffs in Browder v. Gayle, the 1956 case in which the Supreme Court struck down bus segregation in Alabama. Her juvenile record was finally expunged in 2021.',
  },
  {
    kind: 'character',
    id: 'bass_reeves',
    cost: 1,
    identity: ['law', 'grit', 'frontier'],
    era: '1838–1910',
    category: 'historical',
    name: 'Bass Reeves',
    short: 'Reeves',
    influence: 1,
    force: 3,
    tags: ['Black', 'Law'],
    keywords: [],
    reveal: {
      text: 'Confront one neutral Threat here with +1 Force.',
      effect: { type: 'confrontThreat', bonus: 1 },
    },
    blurb: 'Born enslaved, fluent in several Native languages, one of the first Black deputy U.S. Marshals west of the Mississippi. Three thousand arrests, never wounded.',
    history: 'Bass Reeves was born enslaved in Arkansas in 1838 and escaped into Indian Territory during the Civil War. In 1875 Judge Isaac Parker made him a deputy U.S. Marshal, one of the first Black deputies west of the Mississippi. Over thirty-two years he made roughly three thousand arrests, including of his own son, and was never wounded despite many gunfights. Some argue he was the inspiration for the Lone Ranger.',
  },
  {
    kind: 'character',
    id: 'neighbor_kid',
    cost: 0,
    identity: ['youth', 'errands', 'eyes on the street'],
    era: 'Any afternoon',
    category: 'archetype',
    name: 'Neighbor Kid',
    short: 'Kid',
    influence: 1,
    force: 1,
    tags: ['Black', 'Archetype', 'Youth'],
    keywords: [],
    blurb: 'Somebody\'s nephew. Runs the errand, holds the door, sees everything and tells his grandmother.',
  },
  {
    kind: 'character',
    id: 'karen',
    cost: 1,
    category: 'archetype',
    name: 'Karen',
    short: 'Karen',
    influence: 1,
    force: 1,
    tags: ['Archetype', 'Disruption'],
    keywords: [],
    reveal: {
      text: 'The opposing Ready Gate Character here with the highest Influence cannot enter this turn. Then Karen becomes unstable.',
      effect: { type: 'blockOneOpposingGate' },
    },
    passive: {
      text: 'While present, the leading player at her Location loses 1 Influence. At the end of each turn she may relocate to a random Location.',
      unstable: true,
      leaderPenalty: 1,
    },
    identity: ['entitlement', 'disruption', 'unreliability'],
    era: 'Timeless',
    blurb: 'An archetype, not a person. Useful for a turn, then a liability for whoever is winning.',
    history: 'Not a historical person. \'Karen\' is an internet-era archetype for an entitled woman who weaponises complaints and, at the sharp end, the police against Black people going about their day. The name became shorthand after a series of filmed incidents in the 2010s. In the game she is a Character of the same kind as \'Organizer\' or \'OG\': a type, not a biography.',
  },
  {
    kind: 'character',
    id: 'pullman_porter',
    cost: 1,
    category: 'archetype',
    name: 'Pullman Porter',
    short: 'Porter',
    influence: 2,
    force: 2,
    tags: ['Black', 'Archetype', 'Labor'],
    keywords: ['STRAIGHT_INSIDE'],
    established: {
      text: 'You may make one additional Relocation each turn.',
      effect: { type: 'extraRelocation', amount: 1 },
    },
    identity: ['mobility', 'network', 'labor', 'news'],
    era: '1867–1968',
    blurb: 'Porters rode every line in the country, carrying the Chicago Defender and the news of the Great Migration with them.',
    history: 'From the 1860s until the 1960s, the Pullman Company employed tens of thousands of Black men as sleeping-car porters, for decades the largest single employer of Black workers in the United States. The job was hard and underpaid but it was steady, it travelled, and it carried news: porters distributed the Chicago Defender across the South and were among the first Black families of the urban middle class. In 1925 A. Philip Randolph organised them into the Brotherhood of Sleeping Car Porters, the first Black-led union to win a contract with a major American company.',
  },
  {
    kind: 'character',
    id: 'organizer',
    cost: 1,
    category: 'archetype',
    name: 'Organizer',
    short: 'Organizer',
    influence: 2,
    force: 2,
    tags: ['Black', 'Archetype', 'Movement'],
    keywords: [],
    reveal: {
      text: 'Another friendly Fresh Gate Character (here if possible) becomes Ready.',
      effect: { type: 'readyFriendly' },
    },
    established: {
      text: 'You have +1 Energy each turn.',
      effect: { type: 'extraEnergy', amount: 1 },
    },
    identity: ['mobilization', 'community', 'tempo'],
    era: 'Timeless',
    blurb: 'The person with the clipboard, the church basement and the phone tree.',
    history: 'An archetype. The organizer is the person who runs the meeting, keeps the list and makes the phone calls: Ella Baker, who built the NAACP\'s Southern branches and mentored SNCC; Fannie Lou Hamer registering voters in Mississippi; the thousands of unnamed people who made the Montgomery bus boycott run for 381 days. The game\'s Organizer represents that role rather than one person.',
  },
  {
    kind: 'character',
    id: 'og',
    cost: 2,
    category: 'archetype',
    name: 'OG',
    short: 'OG',
    influence: 3,
    force: 3,
    tags: ['Black', 'Archetype', 'Community'],
    keywords: [],
    reveal: {
      text: 'Opposing Gate Characters here cannot enter this turn.',
      effect: { type: 'blockOpposingGatesHere' },
    },
    established: {
      text: 'Opposing Gate Characters here contribute 1 less Influence.',
      effect: { type: 'opposingGateInfluence', amount: 1 },
    },
    identity: ['respect', 'territory', 'gatekeeping'],
    era: 'Timeless',
    blurb: 'Everybody on the block knows who you talk to first.',
    history: 'An archetype. \'OG\' (original gangster, now simply \'original\') is the elder on the block whose standing comes from having been there first and stayed. The game uses the figure for territorial respect: the person you talk to before you do anything on that corner. No single historical figure is intended.',
  },
  {
    kind: 'character',
    id: 'ida_b_wells',
    cost: 3,
    category: 'historical',
    name: 'Ida B. Wells',
    short: 'Ida',
    influence: 4,
    force: 1,
    tags: ['Black', 'Journalist', 'Anti-lynching'],
    keywords: [],
    reveal: {
      text: 'EXPOSE: a Threat here permanently needs 2 less Force to neutralize.',
      effect: { type: 'weakenThreat', amount: 2 },
    },
    established: {
      text: 'Whenever a Threat at this Location is neutralized, Ida gains +2 Influence.',
      effect: { type: 'influenceOnThreatCleared', amount: 2 },
    },
    identity: ['exposure', 'press', 'courage', 'record'],
    era: '1862–1931',
    blurb: 'Investigative journalist who documented lynching with names, dates and evidence when no one else would print them.',
    history: 'Ida B. Wells (1862–1931) was born enslaved in Mississippi and became a journalist and co-owner of the Memphis Free Speech. After three friends were lynched in 1892 she investigated lynching across the South and published the evidence in Southern Horrors and A Red Record, showing that the usual justifications were fabrications. A mob destroyed her press and she continued from Chicago, co-founding the NAACP and organising for women\'s suffrage. She was awarded a posthumous Pulitzer Prize citation in 2020.',
  },
  {
    kind: 'character',
    id: 'queen_nzinga',
    cost: 3,
    category: 'historical',
    name: 'Queen Nzinga',
    short: 'Nzinga',
    influence: 3,
    force: 4,
    tags: ['Black', 'Ndongo', 'Ruler', 'Military'],
    keywords: [],
    reveal: {
      text: "CHALLENGE the opposing Gate Character here with the highest Force. If Nzinga's Force is higher, DISPLACE it to a random other Location's Gate.",
      effect: { type: 'challengeGate' },
    },
    established: {
      text: 'Your Characters here gain +1 Force.',
      effect: { type: 'forceAuraHere', amount: 1 },
    },
    identity: ['resistance', 'diplomacy', 'warfare', 'sovereignty'],
    era: 'c. 1583–1663',
    blurb: 'Queen of Ndongo and Matamba who fought and negotiated against Portuguese colonization for decades.',
    history: 'Nzinga Mbande (c. 1583–1663) was queen of Ndongo and later Matamba, in present-day Angola. She first appears in the record in 1622, negotiating with the Portuguese governor in Luanda; when he offered her no chair, she sat on the back of an attendant. For four decades she fought, allied with and outmanoeuvred the Portuguese and their slave trade, building a state that endured after her death. She is a national symbol in Angola today.',
  },
  {
    kind: 'character',
    id: 'toussaint_louverture',
    cost: 4,
    category: 'historical',
    name: 'Toussaint Louverture',
    short: 'Toussaint',
    influence: 4,
    force: 4,
    tags: ['Black', 'Haiti', 'Revolution', 'Rebellion', 'Military'],
    keywords: [],
    reveal: {
      text: "CHALLENGE the opposing Established Character here with the highest Influence. If Toussaint's Force is higher, it returns to its Gate, Fresh.",
      effect: { type: 'challengeInside' },
    },
    established: {
      text: 'Your Characters here cannot be displaced.',
      effect: { type: 'noDisplaceHere' },
    },
    identity: ['revolution', 'discipline', 'liberation', 'statecraft'],
    era: '1743–1803',
    blurb: 'Leader of the Haitian Revolution, the only slave revolt in history to found an independent state.',
    history: 'Born enslaved in Saint-Domingue around 1743, Toussaint Louverture rose to lead the revolution that began in 1791. He defeated French, Spanish and British forces in turn, abolished slavery across the colony and wrote its 1801 constitution naming himself governor for life. Napoleon sent an army to restore slavery; Toussaint was captured by treachery in 1802 and died in a French prison in the Jura in 1803. His lieutenants finished the war and declared Haiti independent on 1 January 1804.',
  },
  {
    kind: 'character',
    id: 'marcus_garvey',
    cost: 3,
    category: 'historical',
    name: 'Marcus Garvey',
    short: 'Garvey',
    influence: 4,
    force: 2,
    tags: ['Black', 'Pan-African', 'Movement'],
    keywords: [],
    reveal: {
      text: 'Each other friendly Character here gains +1 Influence this turn.',
      effect: { type: 'tempInfluenceAllOthersHere', amount: 1 },
    },
    established: {
      text: 'Characters you relocate out of this Location arrive Ready.',
      effect: { type: 'relocatedOutReady' },
    },
    identity: ['mass movement', 'pride', 'enterprise', 'diaspora'],
    era: '1887–1940',
    blurb: 'Founded the UNIA and the Black Star Line, building the largest mass movement in Black history.',
    history: 'Marcus Garvey (1887–1940), born in Jamaica, founded the Universal Negro Improvement Association in 1914 and moved it to Harlem in 1916. At its peak the UNIA claimed millions of members across the Americas and Africa, published the Negro World and ran the Black Star Line, a shipping company financed by Black shareholders. The line failed, Garvey was convicted of mail fraud in 1923 and deported in 1927, but his ideas of Black pride and self-reliance shaped Rastafari, Pan-Africanism and the civil rights generation.',
  },
  {
    kind: 'character',
    id: 'bessie_coleman',
    cost: 1,
    category: 'historical',
    name: 'Bessie Coleman',
    short: 'Bessie',
    influence: 2,
    force: 3,
    tags: ['Black', 'Aviator'],
    keywords: ['DIRECT_ENTRY'],
    established: {
      text: 'Your Characters here cannot be blocked from entering.',
      effect: { type: 'noBlockHere' },
    },
    identity: ['flight', 'barrier-breaking', 'daring'],
    era: '1892–1926',
    blurb: 'Refused entry to every American flight school, she learned French, trained in Paris and came home a licensed pilot.',
    history: 'Bessie Coleman (1892–1926) was refused by every flight school in the United States because she was Black and a woman. She learned French, sailed to France and in 1921 earned an international pilot\'s licence from the Fédération Aéronautique Internationale, the first Black woman and first Native American woman to do so. Back home she flew barnstorming shows, refused to perform for segregated audiences, and died in a crash in Jacksonville in 1926 while preparing a show. Chicago\'s Bessie Coleman Drive leads to O\'Hare.',
  },
  {
    kind: 'character',
    id: 'sojourner_truth',
    cost: 2,
    category: 'historical',
    name: 'Sojourner Truth',
    short: 'Sojourner',
    influence: 3,
    force: 2,
    tags: ['Black', 'Abolition', 'Suffrage'],
    keywords: [],
    reveal: {
      text: 'SUPPRESS the opposing Established Character here with the highest Influence until the end of next turn.',
      effect: { type: 'suppressInside' },
    },
    established: {
      text: 'Your Characters here cannot be Suppressed.',
      effect: { type: 'noSuppressHere' },
    },
    identity: ['truth', 'testimony', 'faith', 'defiance'],
    era: 'c. 1797–1883',
    blurb: 'Walked away from slavery, sued a white man for her son and won, and spoke truth that silenced rooms.',
    history: 'Born Isabella Baumfree in about 1797 in Ulster County, New York, she walked away from slavery in 1826 with her infant daughter and the next year won a court case to recover her son from an Alabama enslaver, one of the first Black women to win such a case against a white man. She took the name Sojourner Truth in 1843 and spent the rest of her life preaching, speaking for abolition and women\'s rights, and recruiting Black troops during the Civil War. Her 1851 speech in Akron is remembered as \'Ain\'t I a Woman?\'.',
  },
];

CHARACTERS.push({
  kind: 'character',
  id: 'victor_hugo_green',
  cost: 2,
  category: 'historical',
  name: 'Victor Hugo Green',
  short: 'V. H. Green',
  influence: 3,
  force: 1,
  tags: ['Black', 'Travel', 'Publisher'],
  keywords: [],
  reveal: {
    text: 'Draw a card.',
    effect: { type: 'draw', count: 1 },
  },
  established: {
    text: 'Characters you relocate out of this Location arrive Inside their destination (Established), not at the Gates.',
    effect: { type: 'relocatedOutInside' },
  },
  identity: ['safe passage', 'knowledge', 'network', 'interior to interior'],
  era: '1892–1960',
  blurb: 'Publisher of the Green Book, the guide that told Black travelers where they could eat, sleep and buy gas without danger, including how to get through sundown towns.',
    history: 'Victor Hugo Green (1892–1960), a postal worker in Harlem, published The Negro Motorist Green Book from 1936 to 1966. It listed the hotels, restaurants, gas stations and private homes where Black travellers could safely stop, state by state, at a time when a wrong turn at dusk could be dangerous. Green gathered listings through fellow postal workers and readers. The guide stopped publication after the Civil Rights Act of 1964, its stated hope fulfilled: a day when it would no longer be needed.',
});

// ---------- Mythic: African cosmology and diaspora spirituality ----------
const MYTHIC: CharacterDef[] = [
  {
    kind: 'character',
    id: 'anansi',
    cost: 1,
    category: 'mythic',
    name: 'Anansi',
    short: 'Anansi',
    influence: 2,
    force: 1,
    tags: ['Mythic', 'Akan', 'Trickster'],
    keywords: [],
    reveal: {
      text: 'Draw a card. The opposing Ready Gate Character here with the highest Influence is tricked into waiting again (it becomes Fresh).',
      effect: { type: 'refreshOpposingGate' },
    },
    established: {
      text: 'Whenever your opponent plays a Character at this Location, draw a card.',
      effect: { type: 'drawOnOpposingPlay' },
    },
    identity: ['stories', 'cunning', 'small against large'],
    era: 'Akan, timeless',
    blurb: 'The spider who bought all the stories in the world from the sky god with wit alone, and carried them across the Atlantic in the holds of slave ships.',
    history: 'Mythic (fantasy). Anansi is the spider trickster of the Akan people of Ghana and Côte d\'Ivoire, the keeper of all stories, which he won from the sky god Nyame by trapping a python, a leopard, hornets and a fairy with wit alone. Enslaved Akan people carried the tales across the Atlantic, where he became Anancy in Jamaica, Nancy in the Carolina Sea Islands and Aunt Nancy in the American South. The card\'s abilities are invention in his spirit.',
  },
  {
    kind: 'character',
    id: 'shango',
    cost: 3,
    category: 'mythic',
    name: 'Shango',
    short: 'Shango',
    influence: 3,
    force: 5,
    tags: ['Mythic', 'Yoruba', 'Orisha', 'Thunder'],
    keywords: [],
    reveal: {
      text: 'Thunder: CHALLENGE every opposing Gate Character here. Each with lower Force than Shango is displaced to a random other Location.',
      effect: { type: 'challengeAllGates' },
    },
    established: {
      text: 'Your Characters confront Threats here with +2 Force.',
      effect: { type: 'confrontForceHere', amount: 2 },
    },
    identity: ['justice', 'thunder', 'kingship', 'fire'],
    era: 'Yoruba, Oyo',
    blurb: 'Fourth king of Oyo and orisha of thunder and justice, whose double-headed axe and drum travelled to Cuba, Brazil and Trinidad and never fell silent.',
    history: 'Mythic (fantasy). Shango is the orisha of thunder, lightning, fire and justice in Yoruba religion, remembered as the fourth alaafin of the Oyo Empire who became a god. His symbols are the double-headed axe and the bata drum; his colours are red and white. He is honoured as Changó in Cuban Santería, Xangô in Brazilian Candomblé and in Trinidad\'s Shango Baptist tradition. The card\'s abilities are invention in his spirit.',
  },
  {
    kind: 'character',
    id: 'oshun',
    cost: 3,
    category: 'mythic',
    name: 'Oshun',
    short: 'Oshun',
    influence: 4,
    force: 1,
    tags: ['Mythic', 'Yoruba', 'Orisha', 'Rivers'],
    keywords: [],
    reveal: {
      text: 'Sweet water: another friendly Character here gains +1 Influence permanently.',
      effect: { type: 'permInfluenceOther', amount: 1 },
    },
    established: {
      text: 'Your Characters arriving at this Gate become Ready at the end of the turn they arrive.',
      effect: { type: 'freshReadyHere' },
    },
    identity: ['love', 'rivers', 'prosperity', 'diplomacy'],
    era: 'Yoruba, Osogbo',
    blurb: 'Orisha of the river Osun, of fresh water, beauty and wealth. When the other orisha ignored her, the world dried up until they asked her back.',
    history: 'Mythic (fantasy). Oshun is the Yoruba orisha of fresh water, love, fertility and prosperity, associated with the river Osun in Nigeria, where the annual Osun-Osogbo festival draws pilgrims to her sacred grove. In one story the male orisha tried to build the world without her and failed until she was asked back. She is Ochún in Cuba and Oxum in Brazil. The card\'s abilities are invention in her spirit.',
  },
  {
    kind: 'character',
    id: 'yemoja',
    cost: 2,
    category: 'mythic',
    name: 'Yemoja',
    short: 'Yemoja',
    influence: 3,
    force: 3,
    tags: ['Mythic', 'Yoruba', 'Orisha', 'Ocean'],
    keywords: [],
    reveal: {
      text: 'Crossing: bring one friendly Established Character from another Location here. It arrives Inside if there is room, otherwise Ready at the Gates.',
      effect: { type: 'moveFriendlyInsideHere' },
      needsTarget: 'friendlyInsideChar',
    },
    established: {
      text: 'Characters you relocate to this Location arrive Inside.',
      effect: { type: 'relocatedInInside' },
    },
    identity: ['mother', 'ocean', 'crossing', 'protection'],
    era: 'Yoruba, and every shore of the Atlantic',
    blurb: 'Mother of waters, who followed her children across the Middle Passage and is honoured as Yemayá in Cuba and Iemanjá in Brazil.',
    history: 'Mythic (fantasy). Yemoja is the Yoruba mother of waters, patron of women, childbirth and the river Ogun. In the diaspora she became the goddess of the sea, Yemayá in Cuba and Iemanjá in Brazil, where millions bring flowers to the beach for her on 2 February and New Year\'s Eve. The card\'s crossing is a reference to the Middle Passage, over which her children were carried. The abilities are invention in her spirit.',
  },
  {
    kind: 'character',
    id: 'ogun',
    cost: 2,
    category: 'mythic',
    name: 'Ogun',
    short: 'Ogun',
    influence: 2,
    force: 5,
    tags: ['Mythic', 'Yoruba', 'Orisha', 'Iron'],
    keywords: [],
    reveal: {
      text: 'Iron: confront every Threat here with +2 Force.',
      effect: { type: 'confrontAllThreats', bonus: 2 },
    },
    established: {
      text: 'Threats at this Location need 1 less Force to neutralize.',
      effect: { type: 'weakenThreatsHere', amount: 1 },
    },
    identity: ['iron', 'labor', 'war', 'clearing the path'],
    era: 'Yoruba',
    blurb: 'Orisha of iron, the forge and the machete, patron of everyone who works metal, from blacksmiths to the steel mills of Gary.',
    history: 'Mythic (fantasy). Ogun is the Yoruba orisha of iron, the forge, war and labour: blacksmiths, hunters, soldiers, drivers and everyone who works with metal. He cleared the first path through the forest with his machete. He is Ogún in Cuba, Ogum in Brazil and Ogou in Haitian Vodou. The card\'s pairing with Gary, Indiana\'s steel mills is deliberate. The abilities are invention in his spirit.',
  },
  {
    kind: 'character',
    id: 'mami_wata',
    cost: 3,
    category: 'mythic',
    name: 'Mami Wata',
    short: 'Mami Wata',
    influence: 4,
    force: 2,
    tags: ['Mythic', 'Diaspora', 'Water spirit'],
    keywords: [],
    reveal: {
      text: 'Lure: the opposing Gate Character here with the highest Influence is drawn away to a random other Location.',
      effect: { type: 'displaceOpposingGate' },
    },
    established: {
      text: 'Opposing Gate Characters here contribute 1 less Influence.',
      effect: { type: 'opposingGateInfluence', amount: 1 },
    },
    identity: ['allure', 'wealth', 'danger', 'the deep'],
    era: 'West and Central Africa, the Caribbean',
    blurb: 'The water spirit with the snake and the mirror, worshipped from Senegal to Suriname, generous and perilous in equal measure.',
    history: 'Mythic (fantasy). Mami Wata is a water spirit venerated across West, Central and Southern Africa and throughout the diaspora, often shown as a mermaid or a woman with a snake and a mirror. She brings wealth and beauty and demands loyalty; her worship blended with Hindu prints, European mermaid lore and later with Catholic saints. The card\'s abilities are invention in her spirit.',
  },
  {
    kind: 'character',
    id: 'black_jesus',
    cost: 4,
    category: 'mythic',
    name: 'Black Jesus',
    short: 'Black Jesus',
    influence: 5,
    force: 0,
    tags: ['Mythic', 'Spiritual', 'Sanctuary'],
    keywords: [],
    reveal: {
      text: 'Sanctuary: every Block and Suppression at this Location ends, for both players, and every Gate Character here becomes Ready.',
      effect: { type: 'sanctuaryReveal' },
    },
    established: {
      text: 'Threats at this Location cannot touch your Characters: no blocking, no silencing, no displacement. Blessing: every Character you control, at every Location, gains +1 Influence.',
      effect: { type: 'sanctuary', blessing: 1 },
    },
    spawn: {
      type: 'setAt',
      locationId: 'the_tabernacle',
      cardIds: ['richard_allen', 'absalom_jones', 'daniel_payne'],
      headline: 'Richard Allen, Absalom Jones and Daniel Payne are Established at The Tabernacle. Black Jesus appears.',
      cta: 'Continue',
    },
    identity: ['sanctuary', 'liberation', 'grace', 'the church'],
    era: 'The Black church, every era',
    blurb: 'The Christ of the Black church and of liberation theology: the one who sides with the captive. He never fights, and nothing hostile can act on those who stand with him.',
    history: 'Mythic (fantasy). The Black Christ is not a new idea: Coptic Ethiopian art depicted him so for centuries, and in the United States the image runs from the Black church\'s spirituals through Marcus Garvey\'s African Orthodox Church to James Cone\'s Black liberation theology of the 1960s, which held that God sides with the oppressed. The card draws on that tradition. He never fights; his power is sanctuary. The abilities are invention.',
  },
];
CHARACTERS.push(...MYTHIC);

/** Gatherings: never in a deck. They arrive on their own when the board earns them. */
const GATHERINGS: CharacterDef[] = [
  {
    kind: 'character',
    id: 'cookout',
    cost: 2,
    category: 'gathering',
    name: 'The Cookout',
    short: 'Cookout',
    influence: 2,
    force: 1,
    tags: ['Gathering', 'Community'],
    keywords: [],
    established: {
      text: 'Everybody eats: your other Established Characters here gain +1 Influence, and your Characters arriving at this Gate are Ready at once.',
      effect: { type: 'cookout', amount: 1 },
    },
    spawn: {
      type: 'establishedAt',
      locationId: 'great_migration',
      count: 2,
      unique: true,
      headline: 'You have two Characters Established at Great Migration. The Cookout arrives.',
      cta: 'Continue',
    },
    identity: ['community', 'welcome', 'joy'],
    era: 'Timeless',
    blurb: 'Everybody eats. Bring a chair, fix a plate, you are in.',
    history:
      'The Black cookout grows out of emancipation celebrations, church picnics and the Southern barbecue tradition that enslaved and freed Black pitmasters built. The Great Migration carried it to backyards and parks in every Northern city. "Invited to the cookout" became shorthand for being welcomed into the community.',
  },
  {
    kind: 'character',
    id: 'chairteenth',
    cost: 1,
    category: 'gathering',
    name: 'Chairteenth',
    short: 'Chair',
    influence: 1,
    force: 3,
    tags: ['Gathering', 'Defense'],
    keywords: [],
    established: {
      text: 'Your Characters here confront Threats with +1 Force.',
      effect: { type: 'forceAuraHere', amount: 1 },
    },
    spawn: {
      type: 'onReveal',
      locationId: 'montgomery',
      chance: 0.25,
      headline: 'Montgomery, Alabama is revealed. Chairteenth arrives at each player\'s Gates there.',
      cta: 'Continue',
    },
    identity: ['defense', 'solidarity', 'folding chair'],
    era: 'Montgomery, 2023',
    blurb: 'Somebody grabbed a folding chair. The whole dock showed up.',
    history:
      'On August 5, 2023, at Riverfront Park in Montgomery, Alabama, a group of white boaters attacked a Black riverboat co-captain who had asked them to move their pontoon from the Harriott II\'s docking space. Bystanders, most of them Black, rushed to his defense; one man swam across the river to join in, and a folding chair became the day\'s symbol. Videos went viral, several of the boaters were charged with assault, and the internet named the anniversary Chairteenth.',
  },
];
CHARACTERS.push(...GATHERINGS);

// ---------- Cost-flow set: engines, the uprising, and the ones who come back ----------
CHARACTERS.push(
  {
    kind: 'character',
    id: 'booker_t_washington',
    cost: 3,
    identity: ['institution', 'training', 'patience'],
    era: '1856–1915',
    category: 'historical',
    name: 'Booker T. Washington',
    short: 'Booker T.',
    influence: 3,
    force: 2,
    tags: ['Black', 'Founder', 'Education'],
    keywords: [],
    established: {
      text: 'Tuskegee: your Characters cost 1 less Energy to play.',
      effect: { type: 'discountCharacters', amount: 1 },
    },
    blurb: 'Built Tuskegee from a shanty and a church into a campus the students made with their own hands.',
    history:
      'Born enslaved in Franklin County, Virginia, in 1856, Booker Taliaferro Washington worked in salt furnaces and coal mines before walking to Hampton Institute. In 1881 he opened Tuskegee Normal and Industrial Institute in Alabama with thirty students in a shanty; the students built the campus brick by brick. His 1895 Atlanta address and his book Up from Slavery made him the most influential Black American of his day, and his quiet funding of legal challenges to segregation was only discovered after his death in 1915.',
  },
  {
    kind: 'character',
    id: 'george_washington_carver',
    cost: 2,
    identity: ['science', 'soil', 'making much of little'],
    era: 'c. 1864–1943',
    category: 'historical',
    name: 'George Washington Carver',
    short: 'Carver',
    influence: 2,
    force: 2,
    tags: ['Black', 'Science', 'Education'],
    keywords: [],
    reveal: { text: 'Draw a card.', effect: { type: 'draw', count: 1 } },
    established: {
      text: 'Rotation: at the end of each turn, the most expensive card in your hand costs 1 less.',
      effect: { type: 'ripen' },
    },
    blurb: 'Taught the South to rest its soil and found three hundred uses for the peanut.',
    history:
      'Born enslaved near Diamond, Missouri, around 1864 and kidnapped as an infant by raiders, George Washington Carver became the first Black student and then the first Black faculty member at Iowa State. In 1896 Booker T. Washington brought him to Tuskegee, where he ran the agriculture department for forty-seven years, publishing free bulletins on crop rotation, soil restoration and hundreds of uses for peanuts, sweet potatoes and soybeans, and sending a movable school out to sharecroppers by wagon. He died in 1943, leaving his savings to found the Carver Research Foundation.',
  },
  {
    kind: 'character',
    id: 'marie_laveau',
    cost: 3,
    identity: ['vodou', 'new orleans', 'influence'],
    era: '1801–1881',
    category: 'historical',
    name: 'Marie Laveau',
    short: 'Laveau',
    influence: 2,
    force: 2,
    tags: ['Black', 'Faith', 'Vodou'],
    keywords: [],
    reveal: {
      text: 'The opposing Gate Character here with the highest Influence crosses over to your Gates at −1 Influence. You need an open Gate slot.',
      effect: { type: 'stealGate' },
    },
    blurb: 'Hairdresser, healer and the most consulted woman in New Orleans.',
    history:
      'Marie Catherine Laveau was born free in New Orleans in 1801, a Creole of African, French and Native descent. A hairdresser to wealthy households, she became the city\'s best-known Vodou practitioner, leading ceremonies at Congo Square and on Lake Pontchartrain, nursing yellow fever patients and visiting prisoners on death row. Clients across every class came to her for charms, advice and intercession. She died in 1881; her tomb in St. Louis Cemetery No. 1 is still visited.',
  },
  {
    kind: 'character',
    id: 'nanny_of_the_maroons',
    cost: 3,
    identity: ['maroon', 'mountain', 'refuge'],
    era: 'c. 1686–1755',
    category: 'historical',
    name: 'Nanny of the Maroons',
    short: 'Nanny',
    influence: 3,
    force: 4,
    tags: ['Black', 'Jamaica', 'Rebellion', 'Faith'],
    keywords: [],
    established: {
      text: 'Nanny Town: opposing Reveal abilities cannot target your Characters here.',
      effect: { type: 'shieldHere' },
    },
    blurb: 'Led the Windward Maroons from the Blue Mountains and held off the British for a decade.',
    history:
      'Queen Nanny, born in the Gold Coast around 1686, led the Windward Maroons of Jamaica from a mountain settlement the British called Nanny Town. Through the First Maroon War of the 1720s and 1730s her people used the terrain, ambush and abeng horn signals to hold off repeated expeditions, and Maroon tradition credits her with spiritual power as well as command. A 1740 land grant recorded her name. Jamaica named her a National Hero in 1975; she is on the 500-dollar note.',
  },
  {
    kind: 'character',
    id: 'nehanda',
    cost: 3,
    identity: ['spirit medium', 'resistance', 'return'],
    era: 'c. 1840–1898',
    category: 'historical',
    name: 'Nehanda Nyakasikana',
    short: 'Nehanda',
    influence: 3,
    force: 3,
    tags: ['Black', 'Zimbabwe', 'Rebellion', 'Faith'],
    keywords: [],
    passive: {
      text: 'My bones will rise: if she is displaced she returns to your hand instead, and costs 0 the next time you play her. +1 Influence at any Location in Africa.',
      risesAgain: true,
      regionBonus: { region: 'africa', influence: 1 },
    },
    blurb: 'Spirit medium of the Shona who told the colonial court her bones would rise again.',
    history:
      'Charwe Nyakasikana, born around 1840 in the Mazowe valley, was the medium of the ancestral spirit Nehanda among the Shona. In 1896 she and the medium Kaguvi helped lead the First Chimurenga against the British South Africa Company\'s rule in what is now Zimbabwe. Captured in 1897, she refused conversion and was hanged in Salisbury in April 1898. Her reported last words, that her bones would rise again, became a rallying cry of the liberation war of the 1960s and 1970s.',
  },
  {
    kind: 'character',
    id: 'boukman_dutty',
    cost: 7,
    identity: ['uprising', 'ceremony', 'reckoning'],
    era: 'd. 1791',
    category: 'historical',
    name: 'Boukman Dutty',
    short: 'Boukman',
    influence: 4,
    force: 6,
    tags: ['Black', 'Haiti', 'Rebellion', 'Faith', 'Vodou'],
    keywords: [],
    reveal: {
      text: 'Uprising: every Ready Character at your Gates, at every Location, enters Inside now.',
      effect: { type: 'massEnter' },
    },
    passive: {
      text: 'Costs 1 less for each of your Characters on the board with the Rebellion tag.',
      tagDiscount: { tag: 'Rebellion', amount: 1 },
    },
    blurb: 'The Bois Caïman ceremony, and a week later the north of Saint-Domingue was burning.',
    history:
      'Dutty Boukman was a Jamaican-born enslaved man, a Vodou priest and a coachman on a plantation in the northern plain of Saint-Domingue. On the night of 14 August 1791 he presided, with the priestess Cécile Fatiman, over the ceremony at Bois Caïman where enslaved leaders swore to rise. The revolt began a week later and became the Haitian Revolution. Boukman was killed in November 1791 and the French displayed his head in Cap-Français to prove he was dead.',
  },
  {
    kind: 'character',
    id: 'cecile_fatiman',
    cost: 1,
    identity: ['ceremony', 'priestess', 'preparation'],
    era: 'c. 1771–1883',
    category: 'historical',
    name: 'Cécile Fatiman',
    short: 'Fatiman',
    influence: 1,
    force: 2,
    tags: ['Black', 'Haiti', 'Rebellion', 'Faith', 'Vodou'],
    keywords: [],
    reveal: {
      text: 'Ceremony: the most expensive card in your hand costs 2 less.',
      effect: { type: 'reduceHandCost', amount: 2 },
    },
    established: {
      text: 'Your Characters with the Rebellion tag cost 1 less Energy.',
      effect: { type: 'discountTag', tag: 'Rebellion', amount: 1 },
    },
    blurb: 'The mambo at Bois Caïman. Lived to be over a hundred and saw the republic she helped start.',
    history:
      'Cécile Fatiman was a Vodou priestess, a mambo, born around 1771 to an enslaved African mother and a Corsican father. Accounts of the Bois Caïman ceremony of August 1791 describe her presiding alongside Boukman, sacrificing a black pig and being possessed by the lwa Erzulie as the assembled leaders swore their oath. She later married Louis Michel Pierrot, who became president of Haiti, and is said to have lived to 112, dying in 1883.',
  },
  {
    kind: 'character',
    id: 'ayuba_suleiman_diallo',
    cost: 2,
    identity: ['letter', 'return', 'scholarship'],
    era: '1701–1773',
    category: 'historical',
    name: 'Ayuba Suleiman Diallo',
    short: 'Diallo',
    influence: 2,
    force: 1,
    tags: ['Black', 'Faith', 'Islam', 'Travel'],
    keywords: [],
    reveal: {
      text: 'Letter home: return one of your Established Characters at another Location to your hand; it costs 0 the next time you play it. Draw a card.',
      effect: { type: 'returnFriendlyToHand' },
      needsTarget: 'friendlyInsideChar',
    },
    blurb: 'Wrote a letter in Arabic from a Maryland tobacco farm and it carried him home.',
    history:
      'Ayuba Suleiman Diallo, called Job ben Solomon in England, was a Fulani Muslim scholar from Bundu in Senegal, captured and sold in 1731 while himself on a trading journey. Enslaved on a tobacco plantation in Maryland, he wrote a letter in Arabic to his father that reached James Oglethorpe, who bought his freedom. In London he wrote out the Qur\'an from memory, sat for a portrait and returned to Bundu in 1734. His account, published in 1734, is one of the earliest slave narratives.',
  },
  {
    kind: 'character',
    id: 'omar_ibn_said',
    cost: 3,
    identity: ['autobiography', 'reading', 'record'],
    era: 'c. 1770–1864',
    category: 'historical',
    name: 'Omar ibn Said',
    short: 'Omar',
    influence: 2,
    force: 2,
    tags: ['Black', 'Faith', 'Islam', 'Writer'],
    keywords: [],
    reveal: {
      text: 'Autobiography: see every card in your opponent\'s hand.',
      effect: { type: 'peekHand' },
    },
    established: {
      text: 'Scholar: your Events cost 1 less Energy.',
      effect: { type: 'discountEvents', amount: 1 },
    },
    blurb: 'Twenty-five years a scholar in Futa Toro, fifty-six years enslaved in Carolina, and he kept writing.',
    history:
      'Omar ibn Said was born around 1770 in Futa Toro on the Senegal River, studied for twenty-five years and was captured and shipped to Charleston in 1807. He escaped a harsh owner, was jailed in Fayetteville, North Carolina, where he wrote on the cell walls in Arabic, and was then held by the Owen family until his death in 1864. His 1831 autobiography, the only known Arabic-language slave narrative written in the United States, opens with a chapter of the Qur\'an and is held by the Library of Congress.',
  },
);

/** Every Character the board can spawn: Gatherings plus set pieces like Black Jesus. */
export const GATHERING_DEFS: CharacterDef[] = CHARACTERS.filter((c) => c.spawn);

export const CHARACTER_BY_ID: Record<string, CharacterDef> = Object.fromEntries(CHARACTERS.map((c) => [c.id, c]));
