import type { CharacterDef } from '../types';

/**
 * Prototype Character pool. Ability text is the source of truth for players;
 * the `effect` objects are what the engine executes.
 */
export const CHARACTERS: CharacterDef[] = [
  {
    kind: 'character',
    id: 'harriet_tubman',
    cost: 2,
    category: 'historical',
    name: 'Harriet Tubman',
    short: 'Harriet',
    influence: 3,
    force: 2,
    tags: ['Black', 'Abolition'],
    keywords: [],
    reveal: {
      text: "Move one friendly Gate Character to another Location's open Gate. Its waiting progress is preserved.",
      effect: { type: 'moveFriendlyGate' },
      needsTarget: 'friendlyGateCharAndLocation',
    },
    established: {
      text: "The first friendly Character relocated into Harriet's Location each turn becomes Ready immediately.",
      effect: { type: 'readyRelocatedIn' },
    },
    identity: ['freedom', 'movement', 'rescue', 'strategy'],
    era: '1822–1913',
    blurb: 'Conductor of the Underground Railroad who returned again and again to bring people out.',
    history: 'Born Araminta Ross into slavery in Dorchester County, Maryland, around 1822, Harriet Tubman escaped in 1849 and then returned to the South roughly thirteen times, guiding about seventy people to freedom on the Underground Railroad and never losing a passenger. During the Civil War she worked for the Union Army as a nurse, scout and spy, and in June 1863 she guided the Combahee River Raid that freed more than seven hundred people, the first woman to lead an armed assault in the war. She spent her later years in Auburn, New York, campaigning for women\'s suffrage and running a home for the elderly.',
  },
  {
    kind: 'character',
    id: 'frederick_douglass',
    cost: 3,
    category: 'historical',
    name: 'Frederick Douglass',
    short: 'Douglass',
    influence: 4,
    force: 1,
    tags: ['Black', 'Abolition', 'Orator'],
    keywords: [],
    reveal: {
      text: 'Another friendly Character here gains +1 Influence this turn.',
      effect: { type: 'tempInfluenceOther', amount: 1 },
    },
    established: {
      text: 'Your other Characters here gain +1 Influence.',
      effect: { type: 'auraInfluenceOthersHere', amount: 1 },
    },
    identity: ['communication', 'leadership', 'persuasion', 'organizing'],
    era: '1818–1895',
    blurb: 'Escaped slavery and became the most photographed American of the 19th century through the power of his words.',
    history: 'Born enslaved on Maryland\'s Eastern Shore in 1818, Frederick Douglass taught himself to read, escaped to New York in 1838 and became the most famous Black man in the nineteenth-century world. His 1845 Narrative sold tens of thousands of copies, he edited the abolitionist paper The North Star, advised Lincoln on the recruitment of Black soldiers, and later served as U.S. Marshal for the District of Columbia and Minister to Haiti. He sat for more photographs than any other American of his century, because he believed the image of a dignified Black man was itself an argument.',
  },
  {
    kind: 'character',
    id: 'john_brown',
    cost: 2,
    category: 'historical',
    name: 'John Brown',
    short: 'J. Brown',
    influence: 2,
    force: 5,
    tags: ['Ally', 'Abolition'],
    keywords: [],
    reveal: {
      text: 'Confront one neutral Threat here with +2 Force.',
      effect: { type: 'confrontThreat', bonus: 2 },
    },
    established: {
      text: 'When assisting against a Threat, John Brown contributes +1 additional Force.',
      effect: { type: 'assistForceBonus', amount: 1 },
    },
    identity: ['abolition', 'confrontation', 'sacrifice', 'ally'],
    era: '1800–1859',
    blurb: 'Abolitionist who led the raid on Harpers Ferry in 1859, convinced that slavery would not end without force.',
    history: 'A white abolitionist from Connecticut, John Brown believed slavery could only be ended by force. After fighting pro-slavery settlers in Kansas, he led twenty-one men, five of them Black, in a raid on the federal armory at Harpers Ferry, Virginia, on 16 October 1859, hoping to arm an uprising. The raid failed within two days; Brown was tried for treason and hanged on 2 December 1859. His trial speeches and death made him a martyr in the North, and Union soldiers marched to \'John Brown\'s Body\' eighteen months later.',
  },
  {
    kind: 'character',
    id: 'katherine_johnson',
    cost: 2,
    category: 'historical',
    name: 'Katherine Johnson',
    short: 'Katherine',
    influence: 3,
    force: 2,
    tags: ['Black', 'Science'],
    keywords: [],
    reveal: {
      text: 'If any Locations remain hidden, privately learn which Location will reveal next.',
      effect: { type: 'peekNextReveal' },
    },
    established: {
      text: 'Characters you relocate cannot be displaced the turn they arrive.',
      effect: { type: 'relocatedNoDisplace' },
    },
    identity: ['calculation', 'foresight', 'precision'],
    era: '1918–2020',
    blurb: 'NASA mathematician whose trajectory calculations put John Glenn in orbit and Apollo 11 on the Moon.',
    history: 'Katherine Johnson (1918–2020) was a mathematician at NACA and then NASA\'s Langley Research Center. She calculated the trajectory for Alan Shepard\'s 1961 flight, and in 1962 John Glenn asked that she personally re-check the electronic computer\'s figures before his orbital flight. Her work contributed to Apollo 11 and the Space Shuttle. She received the Presidential Medal of Freedom in 2015, and her story reached a wide audience through Hidden Figures.',
  },
  {
    kind: 'character',
    id: 'mansa_musa',
    cost: 4,
    category: 'historical',
    name: 'Mansa Musa',
    short: 'Mansa Musa',
    influence: 5,
    force: 3,
    tags: ['Black', 'Mali', 'Ruler'],
    keywords: [],
    reveal: {
      text: 'If played into a hidden Location, gain +1 Influence when that Location reveals.',
      effect: { type: 'hiddenBonus', amount: 1 },
    },
    established: {
      text: 'The next Character you Establish here gains +1 Influence while Mansa Musa remains here.',
      effect: { type: 'blessNextEstablished', amount: 1 },
    },
    passive: {
      text: 'Gold of Mali: +1 Influence at African Locations (Lagos, Accra).',
      regionBonus: { region: 'africa', influence: 1 },
    },
    identity: ['scale', 'prosperity', 'establishment', 'prestige'],
    era: 'c. 1280–1337',
    blurb: 'Emperor of Mali whose pilgrimage to Mecca spent so much gold it depressed prices across the Mediterranean.',
    history: 'Mansa Musa ruled the Mali Empire from about 1312 to 1337, at the height of its control over the West African gold and salt trade. His 1324 pilgrimage to Mecca, with a caravan reported at tens of thousands of people, spent so much gold in Cairo that the metal\'s value there dropped for years. He returned with scholars and architects, built mosques and madrasas in Timbuktu and Gao, and made Timbuktu a centre of Islamic learning. European maps of the era show him holding a gold nugget.',
  },
  {
    kind: 'character',
    id: 'zora_neale_hurston',
    cost: 2,
    category: 'historical',
    name: 'Zora Neale Hurston',
    short: 'Zora',
    influence: 3,
    force: 1,
    tags: ['Black', 'Writer', 'Harlem Renaissance'],
    keywords: [],
    reveal: {
      text: 'Draw a card.',
      effect: { type: 'draw', count: 1 },
    },
    established: {
      text: 'Your Gate Characters here gain +1 Influence.',
      effect: { type: 'gateInfluenceHere', amount: 1 },
    },
    identity: ['story', 'folklore', 'anthropology', 'voice'],
    era: '1891–1960',
    blurb: 'Novelist and anthropologist who recorded the folklore of the rural South and wrote Their Eyes Were Watching God.',
    history: 'Zora Neale Hurston (1891–1960) grew up in Eatonville, Florida, one of the first all-Black incorporated towns in the country. Trained in anthropology under Franz Boas at Barnard, she collected folklore across the rural South and the Caribbean and published it in Mules and Men. Her 1937 novel Their Eyes Were Watching God was dismissed by some contemporaries and rediscovered decades later, largely through Alice Walker, and is now a cornerstone of American literature.',
  },
  {
    kind: 'character',
    id: 'newsboy',
    cost: 1,
    identity: ['press', 'hustle', 'news'],
    era: '1905–1960',
    category: 'archetype',
    name: 'Newsboy',
    short: 'Newsboy',
    influence: 1,
    force: 1,
    tags: ['Black', 'Archetype', 'Press'],
    keywords: [],
    reveal: {
      text: 'Extra, extra: draw a card.',
      effect: { type: 'draw', count: 1 },
    },
    blurb: 'The Chicago Defender rode south in the bags of Pullman porters and the hands of kids on corners; a paper was the first thing many families bought.',
  },
  {
    kind: 'character',
    id: 'barber',
    cost: 1,
    identity: ['business', 'community', 'talk'],
    era: 'Any Saturday',
    category: 'archetype',
    name: 'Barber',
    short: 'Barber',
    influence: 1,
    force: 2,
    tags: ['Black', 'Archetype', 'Business'],
    keywords: [],
    established: {
      text: 'In and out: Relocations out of this Location do not count against your Relocation limit.',
      effect: { type: 'freeDeparture' },
    },
    blurb: 'The barbershop was bank, newsroom, campaign office and town hall. Everybody passed through, and nobody stayed long.',
  },
  {
    kind: 'character',
    id: 'block_captain',
    cost: 1,
    identity: ['organizing', 'watch', 'neighbors'],
    era: '1960s–',
    category: 'archetype',
    name: 'Block Captain',
    short: 'Captain',
    influence: 1,
    force: 3,
    tags: ['Black', 'Archetype', 'Organizing'],
    keywords: [],
    established: {
      text: 'Your Characters here confront Threats with +1 Force.',
      effect: { type: 'confrontForceHere', amount: 1 },
    },
    blurb: 'Knows every door on the street and who is behind it. When trouble comes, the block already has a plan.',
  },
  {
    kind: 'character',
    id: 'church_mother',
    cost: 1,
    identity: ['faith', 'care', 'order'],
    era: 'Every Sunday',
    category: 'archetype',
    name: 'Church Mother',
    short: 'Mother',
    influence: 1,
    force: 1,
    tags: ['Black', 'Archetype', 'Faith'],
    keywords: [],
    established: {
      text: 'Gains +1 Influence while another of your Characters is at this Location.',
      effect: { type: 'allyBonus', amount: 1 },
    },
    blurb: 'First pew, white gloves, a plate for anyone who came alone. The church ran on the women who ran the church.',
  },
  {
    kind: 'character',
    id: 'claudette_colvin',
    cost: 1,
    identity: ['courage', 'refusal', 'youth', 'justice'],
    era: '1939–',
    category: 'historical',
    name: 'Claudette Colvin',
    short: 'Claudette',
    influence: 2,
    force: 1,
    tags: ['Black', 'Civil Rights'],
    keywords: [],
    reveal: {
      text: 'Keeps her seat: she cannot be displaced this turn.',
      effect: { type: 'holdSeat' },
    },
    blurb: 'Fifteen years old, Montgomery, March 1955. Nine months before Rosa Parks, she refused to move and was dragged off the bus.',
    history: 'On 2 March 1955, fifteen-year-old Claudette Colvin refused to give up her seat on a segregated Montgomery bus and was arrested, nine months before Rosa Parks. Movement leaders passed her over as the public face of the boycott, but she became one of the four plaintiffs in Browder v. Gayle, the 1956 case in which the Supreme Court struck down bus segregation in Alabama. Her juvenile record was finally expunged in 2021.',
  },
  {
    kind: 'character',
    id: 'bass_reeves',
    cost: 1,
    identity: ['law', 'grit', 'frontier'],
    era: '1838–1910',
    category: 'historical',
    name: 'Bass Reeves',
    short: 'Reeves',
    influence: 1,
    force: 3,
    tags: ['Black', 'Law'],
    keywords: [],
    reveal: {
      text: 'Confront one neutral Threat here with +1 Force.',
      effect: { type: 'confrontThreat', bonus: 1 },
    },
    blurb: 'Born enslaved, fluent in several Native languages, one of the first Black deputy U.S. Marshals west of the Mississippi. Three thousand arrests, never wounded.',
    history: 'Bass Reeves was born enslaved in Arkansas in 1838 and escaped into Indian Territory during the Civil War. In 1875 Judge Isaac Parker made him a deputy U.S. Marshal, one of the first Black deputies west of the Mississippi. Over thirty-two years he made roughly three thousand arrests, including of his own son, and was never wounded despite many gunfights. Some argue he was the inspiration for the Lone Ranger.',
  },
  {
    kind: 'character',
    id: 'karen',
    cost: 1,
    category: 'archetype',
    name: 'Karen',
    short: 'Karen',
    influence: 1,
    force: 1,
    tags: ['Archetype', 'Disruption'],
    keywords: [],
    reveal: {
      text: 'The opposing Ready Gate Character here with the highest Influence cannot enter this turn. Then Karen becomes unstable.',
      effect: { type: 'blockOneOpposingGate' },
    },
    passive: {
      text: 'While present, the leading player at her Location loses 1 Influence. At the end of each turn she may relocate to a random Location.',
      unstable: true,
      leaderPenalty: 1,
    },
    identity: ['entitlement', 'disruption', 'unreliability'],
    era: 'Timeless',
    blurb: 'An archetype, not a person. Useful for a turn, then a liability for whoever is winning.',
    history: 'Not a historical person. \'Karen\' is an internet-era archetype for an entitled woman who weaponises complaints and, at the sharp end, the police against Black people going about their day. The name became shorthand after a series of filmed incidents in the 2010s. In the game she is a Character of the same kind as \'Organizer\' or \'OG\': a type, not a biography.',
  },
  {
    kind: 'character',
    id: 'pullman_porter',
    cost: 1,
    category: 'archetype',
    name: 'Pullman Porter',
    short: 'Porter',
    influence: 2,
    force: 2,
    tags: ['Black', 'Archetype', 'Labor'],
    keywords: ['DIRECT_ENTRY'],
    established: {
      text: 'You may make one additional Relocation each turn.',
      effect: { type: 'extraRelocation', amount: 1 },
    },
    identity: ['mobility', 'network', 'labor', 'news'],
    era: '1867–1968',
    blurb: 'Porters rode every line in the country, carrying the Chicago Defender and the news of the Great Migration with them.',
    history: 'From the 1860s until the 1960s, the Pullman Company employed tens of thousands of Black men as sleeping-car porters, for decades the largest single employer of Black workers in the United States. The job was hard and underpaid but it was steady, it travelled, and it carried news: porters distributed the Chicago Defender across the South and were among the first Black families of the urban middle class. In 1925 A. Philip Randolph organised them into the Brotherhood of Sleeping Car Porters, the first Black-led union to win a contract with a major American company.',
  },
  {
    kind: 'character',
    id: 'organizer',
    cost: 1,
    category: 'archetype',
    name: 'Organizer',
    short: 'Organizer',
    influence: 2,
    force: 2,
    tags: ['Black', 'Archetype', 'Movement'],
    keywords: [],
    reveal: {
      text: 'Another friendly Fresh Gate Character (here if possible) becomes Ready.',
      effect: { type: 'readyFriendly' },
    },
    established: {
      text: 'You have +1 Energy each turn.',
      effect: { type: 'extraEnergy', amount: 1 },
    },
    identity: ['mobilization', 'community', 'tempo'],
    era: 'Timeless',
    blurb: 'The person with the clipboard, the church basement and the phone tree.',
    history: 'An archetype. The organizer is the person who runs the meeting, keeps the list and makes the phone calls: Ella Baker, who built the NAACP\'s Southern branches and mentored SNCC; Fannie Lou Hamer registering voters in Mississippi; the thousands of unnamed people who made the Montgomery bus boycott run for 381 days. The game\'s Organizer represents that role rather than one person.',
  },
  {
    kind: 'character',
    id: 'og',
    cost: 2,
    category: 'archetype',
    name: 'OG',
    short: 'OG',
    influence: 3,
    force: 3,
    tags: ['Black', 'Archetype', 'Community'],
    keywords: [],
    reveal: {
      text: 'Opposing Gate Characters here cannot enter this turn.',
      effect: { type: 'blockOpposingGatesHere' },
    },
    established: {
      text: 'Opposing Gate Characters here contribute 1 less Influence.',
      effect: { type: 'opposingGateInfluence', amount: 1 },
    },
    identity: ['respect', 'territory', 'gatekeeping'],
    era: 'Timeless',
    blurb: 'Everybody on the block knows who you talk to first.',
    history: 'An archetype. \'OG\' (original gangster, now simply \'original\') is the elder on the block whose standing comes from having been there first and stayed. The game uses the figure for territorial respect: the person you talk to before you do anything on that corner. No single historical figure is intended.',
  },
  {
    kind: 'character',
    id: 'ida_b_wells',
    cost: 3,
    category: 'historical',
    name: 'Ida B. Wells',
    short: 'Ida',
    influence: 4,
    force: 1,
    tags: ['Black', 'Journalist', 'Anti-lynching'],
    keywords: [],
    reveal: {
      text: 'EXPOSE: a Threat here permanently needs 2 less Force to neutralize.',
      effect: { type: 'weakenThreat', amount: 2 },
    },
    established: {
      text: 'Whenever a Threat at this Location is neutralized, Ida gains +2 Influence.',
      effect: { type: 'influenceOnThreatCleared', amount: 2 },
    },
    identity: ['exposure', 'press', 'courage', 'record'],
    era: '1862–1931',
    blurb: 'Investigative journalist who documented lynching with names, dates and evidence when no one else would print them.',
    history: 'Ida B. Wells (1862–1931) was born enslaved in Mississippi and became a journalist and co-owner of the Memphis Free Speech. After three friends were lynched in 1892 she investigated lynching across the South and published the evidence in Southern Horrors and A Red Record, showing that the usual justifications were fabrications. A mob destroyed her press and she continued from Chicago, co-founding the NAACP and organising for women\'s suffrage. She was awarded a posthumous Pulitzer Prize citation in 2020.',
  },
  {
    kind: 'character',
    id: 'queen_nzinga',
    cost: 3,
    category: 'historical',
    name: 'Queen Nzinga',
    short: 'Nzinga',
    influence: 3,
    force: 4,
    tags: ['Black', 'Ndongo', 'Ruler', 'Military'],
    keywords: [],
    reveal: {
      text: "CHALLENGE the opposing Gate Character here with the highest Force. If Nzinga's Force is higher, DISPLACE it to a random other Location's Gate.",
      effect: { type: 'challengeGate' },
    },
    established: {
      text: 'Your Characters here gain +1 Force.',
      effect: { type: 'forceAuraHere', amount: 1 },
    },
    identity: ['resistance', 'diplomacy', 'warfare', 'sovereignty'],
    era: 'c. 1583–1663',
    blurb: 'Queen of Ndongo and Matamba who fought and negotiated against Portuguese colonization for decades.',
    history: 'Nzinga Mbande (c. 1583–1663) was queen of Ndongo and later Matamba, in present-day Angola. She first appears in the record in 1622, negotiating with the Portuguese governor in Luanda; when he offered her no chair, she sat on the back of an attendant. For four decades she fought, allied with and outmanoeuvred the Portuguese and their slave trade, building a state that endured after her death. She is a national symbol in Angola today.',
  },
  {
    kind: 'character',
    id: 'toussaint_louverture',
    cost: 4,
    category: 'historical',
    name: 'Toussaint Louverture',
    short: 'Toussaint',
    influence: 4,
    force: 4,
    tags: ['Black', 'Haiti', 'Revolution', 'Military'],
    keywords: [],
    reveal: {
      text: "CHALLENGE the opposing Established Character here with the highest Influence. If Toussaint's Force is higher, it returns to its Gate, Fresh.",
      effect: { type: 'challengeInside' },
    },
    established: {
      text: 'Your Characters here cannot be displaced.',
      effect: { type: 'noDisplaceHere' },
    },
    identity: ['revolution', 'discipline', 'liberation', 'statecraft'],
    era: '1743–1803',
    blurb: 'Leader of the Haitian Revolution, the only slave revolt in history to found an independent state.',
    history: 'Born enslaved in Saint-Domingue around 1743, Toussaint Louverture rose to lead the revolution that began in 1791. He defeated French, Spanish and British forces in turn, abolished slavery across the colony and wrote its 1801 constitution naming himself governor for life. Napoleon sent an army to restore slavery; Toussaint was captured by treachery in 1802 and died in a French prison in the Jura in 1803. His lieutenants finished the war and declared Haiti independent on 1 January 1804.',
  },
  {
    kind: 'character',
    id: 'marcus_garvey',
    cost: 3,
    category: 'historical',
    name: 'Marcus Garvey',
    short: 'Garvey',
    influence: 4,
    force: 2,
    tags: ['Black', 'Pan-African', 'Movement'],
    keywords: [],
    reveal: {
      text: 'Each other friendly Character here gains +1 Influence this turn.',
      effect: { type: 'tempInfluenceAllOthersHere', amount: 1 },
    },
    established: {
      text: 'Characters you relocate out of this Location arrive Ready.',
      effect: { type: 'relocatedOutReady' },
    },
    identity: ['mass movement', 'pride', 'enterprise', 'diaspora'],
    era: '1887–1940',
    blurb: 'Founded the UNIA and the Black Star Line, building the largest mass movement in Black history.',
    history: 'Marcus Garvey (1887–1940), born in Jamaica, founded the Universal Negro Improvement Association in 1914 and moved it to Harlem in 1916. At its peak the UNIA claimed millions of members across the Americas and Africa, published the Negro World and ran the Black Star Line, a shipping company financed by Black shareholders. The line failed, Garvey was convicted of mail fraud in 1923 and deported in 1927, but his ideas of Black pride and self-reliance shaped Rastafari, Pan-Africanism and the civil rights generation.',
  },
  {
    kind: 'character',
    id: 'bessie_coleman',
    cost: 1,
    category: 'historical',
    name: 'Bessie Coleman',
    short: 'Bessie',
    influence: 2,
    force: 3,
    tags: ['Black', 'Aviator'],
    keywords: ['DIRECT_ENTRY'],
    established: {
      text: 'Your Characters here cannot be blocked from entering.',
      effect: { type: 'noBlockHere' },
    },
    identity: ['flight', 'barrier-breaking', 'daring'],
    era: '1892–1926',
    blurb: 'Refused entry to every American flight school, she learned French, trained in Paris and came home a licensed pilot.',
    history: 'Bessie Coleman (1892–1926) was refused by every flight school in the United States because she was Black and a woman. She learned French, sailed to France and in 1921 earned an international pilot\'s licence from the Fédération Aéronautique Internationale, the first Black woman and first Native American woman to do so. Back home she flew barnstorming shows, refused to perform for segregated audiences, and died in a crash in Jacksonville in 1926 while preparing a show. Chicago\'s Bessie Coleman Drive leads to O\'Hare.',
  },
  {
    kind: 'character',
    id: 'sojourner_truth',
    cost: 2,
    category: 'historical',
    name: 'Sojourner Truth',
    short: 'Sojourner',
    influence: 3,
    force: 2,
    tags: ['Black', 'Abolition', 'Suffrage'],
    keywords: [],
    reveal: {
      text: 'SUPPRESS the opposing Established Character here with the highest Influence until the end of next turn.',
      effect: { type: 'suppressInside' },
    },
    established: {
      text: 'Your Characters here cannot be Suppressed.',
      effect: { type: 'noSuppressHere' },
    },
    identity: ['truth', 'testimony', 'faith', 'defiance'],
    era: 'c. 1797–1883',
    blurb: 'Walked away from slavery, sued a white man for her son and won, and spoke truth that silenced rooms.',
    history: 'Born Isabella Baumfree in about 1797 in Ulster County, New York, she walked away from slavery in 1826 with her infant daughter and the next year won a court case to recover her son from an Alabama enslaver, one of the first Black women to win such a case against a white man. She took the name Sojourner Truth in 1843 and spent the rest of her life preaching, speaking for abolition and women\'s rights, and recruiting Black troops during the Civil War. Her 1851 speech in Akron is remembered as \'Ain\'t I a Woman?\'.',
  },
];

CHARACTERS.push({
  kind: 'character',
  id: 'victor_hugo_green',
  cost: 2,
  category: 'historical',
  name: 'Victor Hugo Green',
  short: 'V. H. Green',
  influence: 3,
  force: 1,
  tags: ['Black', 'Travel', 'Publisher'],
  keywords: [],
  reveal: {
    text: 'Draw a card.',
    effect: { type: 'draw', count: 1 },
  },
  established: {
    text: 'Characters you relocate out of this Location arrive Inside their destination (Established), not at the Gates.',
    effect: { type: 'relocatedOutInside' },
  },
  identity: ['safe passage', 'knowledge', 'network', 'interior to interior'],
  era: '1892–1960',
  blurb: 'Publisher of the Green Book, the guide that told Black travelers where they could eat, sleep and buy gas without danger, including how to get through sundown towns.',
    history: 'Victor Hugo Green (1892–1960), a postal worker in Harlem, published The Negro Motorist Green Book from 1936 to 1966. It listed the hotels, restaurants, gas stations and private homes where Black travellers could safely stop, state by state, at a time when a wrong turn at dusk could be dangerous. Green gathered listings through fellow postal workers and readers. The guide stopped publication after the Civil Rights Act of 1964, its stated hope fulfilled: a day when it would no longer be needed.',
});

// ---------- Mythic: African cosmology and diaspora spirituality ----------
const MYTHIC: CharacterDef[] = [
  {
    kind: 'character',
    id: 'anansi',
    cost: 1,
    category: 'mythic',
    name: 'Anansi',
    short: 'Anansi',
    influence: 2,
    force: 1,
    tags: ['Mythic', 'Akan', 'Trickster'],
    keywords: [],
    reveal: {
      text: 'Draw a card. The opposing Ready Gate Character here with the highest Influence is tricked into waiting again (it becomes Fresh).',
      effect: { type: 'refreshOpposingGate' },
    },
    established: {
      text: 'Whenever your opponent plays a Character at this Location, draw a card.',
      effect: { type: 'drawOnOpposingPlay' },
    },
    identity: ['stories', 'cunning', 'small against large'],
    era: 'Akan, timeless',
    blurb: 'The spider who bought all the stories in the world from the sky god with wit alone, and carried them across the Atlantic in the holds of slave ships.',
    history: 'Mythic (fantasy). Anansi is the spider trickster of the Akan people of Ghana and Côte d\'Ivoire, the keeper of all stories, which he won from the sky god Nyame by trapping a python, a leopard, hornets and a fairy with wit alone. Enslaved Akan people carried the tales across the Atlantic, where he became Anancy in Jamaica, Nancy in the Carolina Sea Islands and Aunt Nancy in the American South. The card\'s abilities are invention in his spirit.',
  },
  {
    kind: 'character',
    id: 'shango',
    cost: 3,
    category: 'mythic',
    name: 'Shango',
    short: 'Shango',
    influence: 3,
    force: 5,
    tags: ['Mythic', 'Yoruba', 'Orisha', 'Thunder'],
    keywords: [],
    reveal: {
      text: 'Thunder: CHALLENGE every opposing Gate Character here. Each with lower Force than Shango is displaced to a random other Location.',
      effect: { type: 'challengeAllGates' },
    },
    established: {
      text: 'Your Characters confront Threats here with +2 Force.',
      effect: { type: 'confrontForceHere', amount: 2 },
    },
    identity: ['justice', 'thunder', 'kingship', 'fire'],
    era: 'Yoruba, Oyo',
    blurb: 'Fourth king of Oyo and orisha of thunder and justice, whose double-headed axe and drum travelled to Cuba, Brazil and Trinidad and never fell silent.',
    history: 'Mythic (fantasy). Shango is the orisha of thunder, lightning, fire and justice in Yoruba religion, remembered as the fourth alaafin of the Oyo Empire who became a god. His symbols are the double-headed axe and the bata drum; his colours are red and white. He is honoured as Changó in Cuban Santería, Xangô in Brazilian Candomblé and in Trinidad\'s Shango Baptist tradition. The card\'s abilities are invention in his spirit.',
  },
  {
    kind: 'character',
    id: 'oshun',
    cost: 3,
    category: 'mythic',
    name: 'Oshun',
    short: 'Oshun',
    influence: 4,
    force: 1,
    tags: ['Mythic', 'Yoruba', 'Orisha', 'Rivers'],
    keywords: [],
    reveal: {
      text: 'Sweet water: another friendly Character here gains +1 Influence permanently.',
      effect: { type: 'permInfluenceOther', amount: 1 },
    },
    established: {
      text: 'Your Characters arriving at this Gate become Ready at the end of the turn they arrive.',
      effect: { type: 'freshReadyHere' },
    },
    identity: ['love', 'rivers', 'prosperity', 'diplomacy'],
    era: 'Yoruba, Osogbo',
    blurb: 'Orisha of the river Osun, of fresh water, beauty and wealth. When the other orisha ignored her, the world dried up until they asked her back.',
    history: 'Mythic (fantasy). Oshun is the Yoruba orisha of fresh water, love, fertility and prosperity, associated with the river Osun in Nigeria, where the annual Osun-Osogbo festival draws pilgrims to her sacred grove. In one story the male orisha tried to build the world without her and failed until she was asked back. She is Ochún in Cuba and Oxum in Brazil. The card\'s abilities are invention in her spirit.',
  },
  {
    kind: 'character',
    id: 'yemoja',
    cost: 2,
    category: 'mythic',
    name: 'Yemoja',
    short: 'Yemoja',
    influence: 3,
    force: 3,
    tags: ['Mythic', 'Yoruba', 'Orisha', 'Ocean'],
    keywords: [],
    reveal: {
      text: 'Crossing: bring one friendly Established Character from another Location here. It arrives Inside if there is room, otherwise Ready at the Gates.',
      effect: { type: 'moveFriendlyInsideHere' },
      needsTarget: 'friendlyInsideChar',
    },
    established: {
      text: 'Characters you relocate to this Location arrive Inside.',
      effect: { type: 'relocatedInInside' },
    },
    identity: ['mother', 'ocean', 'crossing', 'protection'],
    era: 'Yoruba, and every shore of the Atlantic',
    blurb: 'Mother of waters, who followed her children across the Middle Passage and is honoured as Yemayá in Cuba and Iemanjá in Brazil.',
    history: 'Mythic (fantasy). Yemoja is the Yoruba mother of waters, patron of women, childbirth and the river Ogun. In the diaspora she became the goddess of the sea, Yemayá in Cuba and Iemanjá in Brazil, where millions bring flowers to the beach for her on 2 February and New Year\'s Eve. The card\'s crossing is a reference to the Middle Passage, over which her children were carried. The abilities are invention in her spirit.',
  },
  {
    kind: 'character',
    id: 'ogun',
    cost: 2,
    category: 'mythic',
    name: 'Ogun',
    short: 'Ogun',
    influence: 2,
    force: 5,
    tags: ['Mythic', 'Yoruba', 'Orisha', 'Iron'],
    keywords: [],
    reveal: {
      text: 'Iron: confront every Threat here with +2 Force.',
      effect: { type: 'confrontAllThreats', bonus: 2 },
    },
    established: {
      text: 'Threats at this Location need 1 less Force to neutralize.',
      effect: { type: 'weakenThreatsHere', amount: 1 },
    },
    identity: ['iron', 'labor', 'war', 'clearing the path'],
    era: 'Yoruba',
    blurb: 'Orisha of iron, the forge and the machete, patron of everyone who works metal, from blacksmiths to the steel mills of Gary.',
    history: 'Mythic (fantasy). Ogun is the Yoruba orisha of iron, the forge, war and labour: blacksmiths, hunters, soldiers, drivers and everyone who works with metal. He cleared the first path through the forest with his machete. He is Ogún in Cuba, Ogum in Brazil and Ogou in Haitian Vodou. The card\'s pairing with Gary, Indiana\'s steel mills is deliberate. The abilities are invention in his spirit.',
  },
  {
    kind: 'character',
    id: 'mami_wata',
    cost: 3,
    category: 'mythic',
    name: 'Mami Wata',
    short: 'Mami Wata',
    influence: 4,
    force: 2,
    tags: ['Mythic', 'Diaspora', 'Water spirit'],
    keywords: [],
    reveal: {
      text: 'Lure: the opposing Gate Character here with the highest Influence is drawn away to a random other Location.',
      effect: { type: 'displaceOpposingGate' },
    },
    established: {
      text: 'Opposing Gate Characters here contribute 1 less Influence.',
      effect: { type: 'opposingGateInfluence', amount: 1 },
    },
    identity: ['allure', 'wealth', 'danger', 'the deep'],
    era: 'West and Central Africa, the Caribbean',
    blurb: 'The water spirit with the snake and the mirror, worshipped from Senegal to Suriname, generous and perilous in equal measure.',
    history: 'Mythic (fantasy). Mami Wata is a water spirit venerated across West, Central and Southern Africa and throughout the diaspora, often shown as a mermaid or a woman with a snake and a mirror. She brings wealth and beauty and demands loyalty; her worship blended with Hindu prints, European mermaid lore and later with Catholic saints. The card\'s abilities are invention in her spirit.',
  },
  {
    kind: 'character',
    id: 'black_jesus',
    cost: 4,
    category: 'mythic',
    name: 'Black Jesus',
    short: 'Black Jesus',
    influence: 5,
    force: 0,
    tags: ['Mythic', 'Spiritual', 'Sanctuary'],
    keywords: [],
    reveal: {
      text: 'Sanctuary: every Block and Suppression at this Location ends, for both players, and every Gate Character here becomes Ready.',
      effect: { type: 'sanctuaryReveal' },
    },
    established: {
      text: 'Threats at this Location cannot touch your Characters: no blocking, no silencing, no displacement.',
      effect: { type: 'sanctuary' },
    },
    identity: ['sanctuary', 'liberation', 'grace', 'the church'],
    era: 'The Black church, every era',
    blurb: 'The Christ of the Black church and of liberation theology: the one who sides with the captive. He never fights, and nothing hostile can act on those who stand with him.',
    history: 'Mythic (fantasy). The Black Christ is not a new idea: Coptic Ethiopian art depicted him so for centuries, and in the United States the image runs from the Black church\'s spirituals through Marcus Garvey\'s African Orthodox Church to James Cone\'s Black liberation theology of the 1960s, which held that God sides with the oppressed. The card draws on that tradition. He never fights; his power is sanctuary. The abilities are invention.',
  },
];
CHARACTERS.push(...MYTHIC);

/** Gatherings: never in a deck. They arrive on their own when the board earns them. */
const GATHERINGS: CharacterDef[] = [
  {
    kind: 'character',
    id: 'cookout',
    cost: 2,
    category: 'gathering',
    name: 'The Cookout',
    short: 'Cookout',
    influence: 2,
    force: 1,
    tags: ['Gathering', 'Community'],
    keywords: [],
    established: {
      text: 'Everybody eats: your other Established Characters here gain +1 Influence, and your Characters arriving at this Gate are Ready at once.',
      effect: { type: 'cookout', amount: 1 },
    },
    spawn: {
      type: 'establishedAt',
      locationId: 'great_migration',
      count: 2,
      unique: true,
      headline: 'Two of yours made it north. Word spreads, the grill is lit.',
      cta: 'Fix a plate',
    },
    identity: ['community', 'welcome', 'joy'],
    era: 'Timeless',
    blurb: 'Everybody eats. Bring a chair, fix a plate, you are in.',
    history:
      'The Black cookout grows out of emancipation celebrations, church picnics and the Southern barbecue tradition that enslaved and freed Black pitmasters built. The Great Migration carried it to backyards and parks in every Northern city. "Invited to the cookout" became shorthand for being welcomed into the community.',
  },
  {
    kind: 'character',
    id: 'chairteenth',
    cost: 1,
    category: 'gathering',
    name: 'Chairteenth',
    short: 'Chair',
    influence: 1,
    force: 3,
    tags: ['Gathering', 'Defense'],
    keywords: [],
    established: {
      text: 'Your Characters here confront Threats with +1 Force.',
      effect: { type: 'forceAuraHere', amount: 1 },
    },
    spawn: {
      type: 'onReveal',
      locationId: 'juneteenth',
      headline: 'Juneteenth is on the board. Somebody brought a folding chair.',
      cta: 'Grab a chair',
    },
    identity: ['defense', 'solidarity', 'folding chair'],
    era: 'Montgomery, 2023',
    blurb: 'Somebody grabbed a folding chair. The whole dock showed up.',
    history:
      'On August 5, 2023, at Riverfront Park in Montgomery, Alabama, a group of white boaters attacked a Black riverboat co-captain who had asked them to move their pontoon from the Harriott II\'s docking space. Bystanders, most of them Black, rushed to his defense; one man swam across the river to join in, and a folding chair became the day\'s symbol. Videos went viral, several of the boaters were charged with assault, and the internet named the anniversary Chairteenth.',
  },
];
CHARACTERS.push(...GATHERINGS);
export const GATHERING_DEFS = GATHERINGS;

export const CHARACTER_BY_ID: Record<string, CharacterDef> = Object.fromEntries(CHARACTERS.map((c) => [c.id, c]));
