import type { EventDef } from '../types';

export const EVENTS: EventDef[] = [
  {
    kind: 'event',
    id: 'reparations',
    name: 'Reparations',
    short: 'Reparations',
    cost: 1,
    text: 'Choose a Location with an open Gate slot: +1 Influence there this turn for each Setback suffered this match (max +4). In the Americas: +1 more.',
    effect: { type: 'reparations', max: 4, bonus: { region: 'americas', influence: 1 } },
    needsLocation: true,
    blurb: 'Only neutral historical harm counts. What the opponent did to you is not the same thing. The debt is owed where it was run up.',
  },
  {
    kind: 'event',
    id: 'community_defense',
    name: 'Community Defense',
    short: 'Defense',
    cost: 2,
    text: 'This turn none of your Characters, anywhere, can be blocked or displaced. Choose a Location with an open Gate slot: your Characters there also confront Threats with +2 Force.',
    effect: { type: 'communityDefense', force: 2 },
    needsLocation: true,
    blurb: 'Deacons for Defense, armed porches, neighbors who showed up.',
    history:
      'The Deacons for Defense and Justice formed in Jonesboro, Louisiana, in 1964 and spread to Bogalusa and beyond: armed Black men, many of them veterans, who escorted civil rights workers and guarded their neighborhoods against Klan attacks when the police would not. Their presence let nonviolent campaigns keep going.',
  },
  {
    kind: 'event',
    id: 'the_ancestors',
    name: 'The Ancestors',
    short: 'Ancestors',
    cost: 0,
    text: 'Play it while planning: the Ancestors show you your opponent\'s plan for this turn and every danger the board is about to spring. Choose a Location with an open Gate slot. In Africa: your Characters there gain +1 Influence this turn.',
    effect: { type: 'ancestors', bonus: { region: 'africa', influence: 1 } },
    needsLocation: true,
    blurb: 'Never in a deck. In one match out of four they come to whoever holds three Characters Inside at Accra, Ghana.',
    spawn: { type: 'insideAt', chance: 0.25, locationId: 'accra_ghana', count: 3, headline: 'You have three Characters Inside at Accra, Ghana. The Ancestors come to your hand.', cta: 'Continue', into: 'hand' },
  },
  {
    kind: 'event',
    id: 'word_of_mouth',
    name: 'Word of Mouth',
    short: 'Word',
    cost: 0,
    text: 'Draw a card. Choose a Location with an open Gate slot: where you have 2 or more Characters, draw 2 instead.',
    effect: { type: 'draw', count: 1, bonus: { crowd: 2, extra: 1 } },
    needsLocation: true,
    blurb: 'Free, fast and usually right. It travels further where more of your people are.',
  },
  {
    kind: 'event',
    id: 'persuade',
    name: 'Persuade',
    short: 'Persuade',
    cost: 3,
    curse: true,
    text: 'Curse. Every opposing Gate Character loses 1 Influence this turn. Choose a Location with an open Gate slot: the opposing Gate Character there with the lowest Influence crosses over to your Gates at −1 Influence.',
    effect: { type: 'persuade', drain: 1 },
    needsLocation: true,
    blurb: 'Everybody has a price, a grievance or a cousin. Find the one that opens the door.',
  },
];

export const EVENT_BY_ID: Record<string, EventDef> = Object.fromEntries(EVENTS.map((e) => [e.id, e]));
