import type { LocationDef } from '../types';

export const LOCATIONS: LocationDef[] = [
  {
    id: 'greenwood',
    name: 'Greenwood District',
    era: 'Tulsa, 1921',
    rule: 'Established Characters here gain +1 Influence. On Turn 4 a Mob arrives.',
    blurb: '"Black Wall Street" — a prosperous district destroyed by a white mob in 1921 while authorities looked away.',
    effect: { type: 'insideInfluence', amount: 1 },
    timedThreat: { turn: 4, threatId: 'mob' },
    region: 'americas',
  },
  {
    id: 'harpers_ferry',
    name: 'Harpers Ferry',
    era: 'Virginia, 1859',
    rule: 'Characters confronting Threats here receive +2 Force. Reveals with a Paddy Roller in the area.',
    blurb: 'Site of John Brown\'s raid on the federal armory, the spark that made the coming war unavoidable.',
    effect: { type: 'confrontForce', amount: 2 },
    spawnOnReveal: 'paddy_roller',
    region: 'americas',
  },
  {
    id: 'black_star',
    name: 'The Black Star',
    era: 'Atlantic, 1919',
    rule: 'A ship. Characters you relocate out of here arrive Ready. Three turns after it reveals, the ship arrives in Accra: everyone aboard gains +1 Influence, Gate Characters walk straight in, and any Threat here is cleared.',
    blurb: 'Marcus Garvey\'s Black Star Line: ships owned by Black people, connecting the diaspora on its own terms. It never reached Africa, but the star did.',
    effect: { type: 'relocatedOutReady' },
    transformsInto: { id: 'accra_ghana', afterTurns: 3 },
    region: 'atlantic',
  },
  {
    id: 'accra_ghana',
    name: 'Accra, Ghana',
    region: 'africa',
    era: 'Independence, 1957',
    rule: 'The Black Star has landed. Characters relocated here arrive Ready, and Threats cannot appear here.',
    blurb: 'On 6 March 1957 Kwame Nkrumah raised a flag with a black star at its centre, in Garvey\'s honour, and named the new nation\'s shipping line the Black Star Line.',
    effect: { type: 'relocatedInReady' },
    notInPool: true,
    noThreats: true,
  },
  {
    id: 'great_migration',
    name: 'Great Migration',
    era: '1916–1970',
    rule: 'The first Character relocated here each turn enters immediately.',
    blurb: 'Six million people left the rural South for northern and western cities, remaking America.',
    effect: { type: 'firstRelocatedEnters' },
    region: 'americas',
  },
  {
    id: 'juneteenth',
    name: 'Juneteenth',
    era: 'Galveston, 1865',
    rule: 'Gate Characters here become Ready the turn they arrive (including when this Location reveals).',
    blurb: 'June 19th, 1865: the day freedom finally reached Texas, two years after it was declared.',
    effect: { type: 'readyOnArrival' },
    region: 'americas',
  },
  {
    id: 'sundown_town',
    name: 'Sundown Town',
    era: '1890–1968',
    rule: 'Characters arriving at these Gates are displaced to a random other Location at the end of the turn (Setback). At night (even turns) nobody relocates out: curfew until morning. Nothing happens on the turn it reveals. Direct Entry and Characters arriving Inside are safe.',
    blurb: 'Thousands of towns enforced, by sign, ordinance or violence, that Black people be gone by nightfall.',
    effect: { type: 'displaceFreshAtEnd' },
    curfew: true,
    weight: 0.35,
    region: 'americas',
  },
  {
    id: 'middle_passage',
    name: 'The Middle Passage',
    era: 'Atlantic, 1526–1867',
    rule: 'The crossing. Nobody goes Inside here. At the end of each turn every Character at these Gates loses 1 Influence for good (never below 0). Whoever leaves here arrives Ready and carries +1 Influence for good: what survived the crossing came with them. The DeWolf Trade ships people here.',
    blurb: 'Twelve and a half million people were carried across the Atlantic in chains, and ten and a half million landed. What they carried, they kept: the languages, the faiths, the stories, the songs.',
    history:
      'Between 1526 and 1867 about 12.5 million Africans were forced aboard ships bound for the Americas; roughly 10.7 million survived the crossing. Voyages took one to three months, with people chained below decks in spaces too low to sit upright, and dysentery, smallpox and despair killed one in eight on average. Olaudah Equiano, Ottobah Cugoano and the survivors of the Amistad left the first-hand accounts; the ledgers of the traders, the DeWolfs among them, left the numbers. What the survivors carried is the other half of the ledger: Anansi\'s stories reached Jamaica and the Carolina Sea Islands, the orisha crossed to Cuba, Brazil and Haiti, Islam survived in men like Omar ibn Said and Ayuba Suleiman Diallo, and the rhythms became the blues, jazz and everything after. The card plays it that way: the crossing costs, and whoever comes through it lands standing and carries something that stays.',
    effect: { type: 'crossing', toll: 1 },
    noThreats: true,
    weight: 0.3,
    region: 'atlantic',
  },
  {
    id: 'charleston_1822',
    name: 'Charleston, 1822',
    era: 'South Carolina, 1822',
    rule: 'The plot is betrayed: at the end of each turn, the Fresh Gate Character here with the lowest Influence changes sides (a tie goes against the leader). A turncoat can turn back later. Nothing happens on the turn it reveals.',
    blurb: "Denmark Vesey's rising was set for July. Two informants ended it in June, and thirty-five people hanged.",
    effect: { type: 'turncoatAtEnd' },
    weight: 0.35,
    region: 'americas',
  },
  {
    id: 'lagos',
    name: 'Lagos',
    era: 'Eko, today',
    rule: 'Danfo: Relocations out of Lagos do not count against your Relocation limit, and Characters who leave arrive Ready. No Housing Restriction here.',
    blurb: 'Twenty million people, Nollywood, Afrobeats, Fela\'s Kalakuta Republic and the yellow danfo buses that never stop. Lagos no dey carry last.',
    effect: { type: 'hub' },
    region: 'africa',
    immuneThreats: ['housing_restriction'],
  },
  {
    id: 'gary_indiana',
    name: 'Gary, Indiana',
    era: 'Steel City, 1906–',
    rule: 'Steel: your Characters here gain +1 Force. Soul: a player with five Characters here (Gates and Inside) gains +1 Influence on each of them.',
    blurb: 'Built by U.S. Steel, filled by the Great Migration. Joe Jackson ran a crane at Gary Works and drilled five boys in the living room at 2300 Jackson Street; in 1972 ten thousand people came for the National Black Political Convention.',
    effect: { type: 'steelAndSoul', force: 1, fiveBonus: 1 },
    region: 'americas',
  },
  {
    id: 'justice_system',
    name: 'The Justice System',
    era: '1865–',
    rule: 'Once a Character goes Inside here, it cannot relocate out for 2 turns.',
    blurb: 'The Thirteenth Amendment kept one exception, "as a punishment for crime." Convict leasing, chain gangs and mass incarceration have run on it ever since.',
    effect: { type: 'lockInside', turns: 2 },
    weight: 0.6,
    region: 'americas',
  },
  {
    id: 'the_tabernacle',
    name: 'The Tabernacle',
    era: '1794–',
    rule: 'Sanctuary: your Characters here cannot be displaced. Establish Richard Allen, Absalom Jones and Daniel Payne here and Black Jesus appears.',
    blurb: 'Mother Bethel, Philadelphia, 1794: Richard Allen walked out rather than pray in the back. The Black church has been meeting house, school, bank and headquarters ever since.',
    effect: { type: 'noDisplace' },
    weight: 0.8,
    region: 'americas',
  },
  {
    id: 'montgomery',
    name: 'Montgomery, Alabama',
    era: '1955–1956',
    rule: 'The boycott: Characters who relocate out of Montgomery arrive Ready.',
    blurb: 'For 381 days the buses ran empty. Forty thousand people walked, carpooled and waited, and the seats stopped being the point.',
    effect: { type: 'relocatedOutReady' },
    weight: 0.9,
    region: 'americas',
  },
  {
    id: 'oak_bluffs',
    name: 'Oak Bluffs',
    era: "Martha's Vineyard, 1912–",
    rule: 'The Inkwell: at the end of each turn, each player with 2 or more Characters Inside here gains +1 Energy next turn. Threats never appear here.',
    blurb: "Shearer Cottage opened to Black guests in 1912 when the island's hotels would not. A century of summers followed: the Inkwell, the gingerbread cottages, families who came back every August.",
    effect: { type: 'restEnergy', count: 2, amount: 1 },
    noThreats: true,
    region: 'americas',
    weight: 0.9,
  },
  {
    id: 'the_stroll',
    name: 'The Stroll',
    era: 'Chicago, 1910s–20s',
    rule: 'After dark (even turns) your Characters Inside here gain +1 Influence. By day it is just a street.',
    blurb: "State Street from 26th to 39th, the Black Belt's night strip: theaters, cabarets, and everybody out walking.",
    history:
      "The Stroll was State Street between about 26th and 39th, the heart of Chicago's Black Belt in the 1910s and 1920s. Newcomers from the South found the Pekin Theatre, the Vendome, the Dreamland Café and the Royal Gardens, where King Oliver's band played and a young Louis Armstrong joined in 1922. Langston Hughes remembered South State Street \"in its glory then, a teeming Negro street with crowded theaters, restaurants, and cabarets.\" By the thirties the action had moved south to 47th Street.",
    effect: { type: 'nightInside', amount: 1 },
    region: 'americas',
    weight: 0.9,
  },
];

export const UNKNOWN_LOCATION: LocationDef = {
  id: 'unknown',
  name: 'Hidden Location',
  era: '',
  rule: 'This Location has not been revealed.',
  blurb: '',
  effect: { type: 'none' },
  hidden: true,
};

export const LOCATION_BY_ID: Record<string, LocationDef> = Object.fromEntries(
  [...LOCATIONS, UNKNOWN_LOCATION].map((l) => [l.id, l]),
);
