import type { LocationDef } from '../types';

export const LOCATIONS: LocationDef[] = [
  {
    id: 'greenwood',
    name: 'Greenwood District',
    era: 'Tulsa, 1921',
    rule: 'Established Characters here gain +1 Influence. On Turn 4 a Mob arrives.',
    blurb: '"Black Wall Street" — a prosperous district destroyed by a white mob in 1921 while authorities looked away.',
    effect: { type: 'insideInfluence', amount: 1 },
    timedThreat: { turn: 4, threatId: 'mob' },
    region: 'americas',
  },
  {
    id: 'harpers_ferry',
    name: 'Harpers Ferry',
    era: 'Virginia, 1859',
    rule: 'Characters confronting Threats here receive +2 Force. Reveals with a Paddy Roller in the area.',
    blurb: 'Site of John Brown\'s raid on the federal armory, the spark that made the coming war unavoidable.',
    effect: { type: 'confrontForce', amount: 2 },
    spawnOnReveal: 'paddy_roller',
    region: 'americas',
  },
  {
    id: 'black_star',
    name: 'The Black Star',
    era: 'Atlantic, 1919',
    rule: 'A ship. Characters you relocate out of here arrive Ready. Three turns after it reveals, the ship arrives in Accra: everyone aboard gains +1 Influence, Gate Characters walk straight in, and any Threat here is cleared.',
    blurb: 'Marcus Garvey\'s Black Star Line: ships owned by Black people, connecting the diaspora on its own terms. It never reached Africa, but the star did.',
    effect: { type: 'relocatedOutReady' },
    transformsInto: { id: 'accra_ghana', afterTurns: 3 },
    region: 'atlantic',
  },
  {
    id: 'accra_ghana',
    name: 'Accra, Ghana',
    region: 'africa',
    era: 'Independence, 1957',
    rule: 'The Black Star has landed. Characters relocated here arrive Ready, and Threats cannot appear here.',
    blurb: 'On 6 March 1957 Kwame Nkrumah raised a flag with a black star at its centre, in Garvey\'s honour, and named the new nation\'s shipping line the Black Star Line.',
    effect: { type: 'relocatedInReady' },
    notInPool: true,
    noThreats: true,
  },
  {
    id: 'great_migration',
    name: 'Great Migration',
    era: '1916–1970',
    rule: 'The first Character relocated here each turn enters immediately.',
    blurb: 'Six million people left the rural South for northern and western cities, remaking America.',
    effect: { type: 'firstRelocatedEnters' },
    region: 'americas',
  },
  {
    id: 'juneteenth',
    name: 'Juneteenth',
    era: 'Galveston, 1865',
    rule: 'Gate Characters here become Ready the turn they arrive (including when this Location reveals).',
    blurb: 'June 19th, 1865: the day freedom finally reached Texas, two years after it was declared.',
    effect: { type: 'readyOnArrival' },
    region: 'americas',
  },
  {
    id: 'sundown_town',
    name: 'Sundown Town',
    era: '1890–1968',
    rule: 'Characters arriving at these Gates are displaced to a random other Location at the end of the turn (Setback). At night (even turns) nobody relocates out: curfew until morning. Nothing happens on the turn it reveals. Direct Entry and Characters arriving Inside are safe.',
    blurb: 'Thousands of towns enforced, by sign, ordinance or violence, that Black people be gone by nightfall.',
    effect: { type: 'displaceFreshAtEnd' },
    curfew: true,
    weight: 0.35,
    region: 'americas',
  },
  {
    id: 'middle_passage',
    name: 'The Middle Passage',
    era: 'Atlantic, 1526–1867',
    rule: 'The crossing. Nobody goes Inside here. At the end of each turn every Character at these Gates loses 1 Influence for good (never below 0). Whoever leaves here arrives Ready and carries +1 Influence for good: what survived the crossing came with them. The DeWolf Trade ships people here.',
    blurb: 'Twelve and a half million people were carried across the Atlantic in chains, and ten and a half million landed. What they carried, they kept: the languages, the faiths, the stories, the songs.',
    history:
      'Between 1526 and 1867 about 12.5 million Africans were forced aboard ships bound for the Americas; roughly 10.7 million survived the crossing. Voyages took one to three months, with people chained below decks in spaces too low to sit upright, and dysentery, smallpox and despair killed one in eight on average. Olaudah Equiano, Ottobah Cugoano and the survivors of the Amistad left the first-hand accounts; the ledgers of the traders, the DeWolfs among them, left the numbers. What the survivors carried is the other half of the ledger: Anansi\'s stories reached Jamaica and the Carolina Sea Islands, the orisha crossed to Cuba, Brazil and Haiti, Islam survived in men like Omar ibn Said and Ayuba Suleiman Diallo, and the rhythms became the blues, jazz and everything after. The card plays it that way: the crossing costs, and whoever comes through it lands standing and carries something that stays.',
    effect: { type: 'crossing', toll: 1 },
    noThreats: true,
    weight: 0.3,
    region: 'atlantic',
  },
  {
    id: 'charleston_1822',
    name: 'Charleston, 1822',
    era: 'South Carolina, 1822',
    rule: 'The plot is betrayed: at the end of each turn, the Fresh Gate Character here with the lowest Influence changes sides (a tie goes against the leader). A turncoat can turn back later. Nothing happens on the turn it reveals.',
    blurb: "Denmark Vesey's rising was set for July. Two informants ended it in June, and thirty-five people hanged.",
    effect: { type: 'turncoatAtEnd' },
    weight: 0.35,
    region: 'americas',
  },
  {
    id: 'lagos',
    name: 'Lagos',
    era: 'Eko, today',
    rule: 'Danfo: Relocations out of Lagos do not count against your Relocation limit, and Characters who leave arrive Ready. No Housing Restriction here.',
    blurb: 'Twenty million people, Nollywood, Afrobeats, Fela\'s Kalakuta Republic and the yellow danfo buses that never stop. Lagos no dey carry last.',
    effect: { type: 'hub' },
    region: 'africa',
    immuneThreats: ['housing_restriction'],
  },
  {
    id: 'gary_indiana',
    name: 'Gary, Indiana',
    era: 'Steel City, 1906–',
    rule: 'Steel: your Characters here gain +1 Force. Soul: a player with five Characters here (Gates and Inside) gains +1 Influence on each of them.',
    blurb: 'Built by U.S. Steel, filled by the Great Migration. Joe Jackson ran a crane at Gary Works and drilled five boys in the living room at 2300 Jackson Street; in 1972 ten thousand people came for the National Black Political Convention.',
    effect: { type: 'steelAndSoul', force: 1, fiveBonus: 1 },
    region: 'americas',
  },
  {
    id: 'justice_system',
    name: 'The Justice System',
    era: '1865–',
    rule: 'Once a Character goes Inside here, it cannot relocate out for 2 turns.',
    blurb: 'The Thirteenth Amendment kept one exception, "as a punishment for crime." Convict leasing, chain gangs and mass incarceration have run on it ever since.',
    effect: { type: 'lockInside', turns: 2 },
    weight: 0.6,
    region: 'americas',
  },
  {
    id: 'the_tabernacle',
    name: 'The Tabernacle',
    era: '1794–',
    rule: 'Sanctuary: your Characters here cannot be displaced. Establish Richard Allen, Absalom Jones and Daniel Payne here and Black Jesus appears.',
    blurb: 'Mother Bethel, Philadelphia, 1794: Richard Allen walked out rather than pray in the back. The Black church has been meeting house, school, bank and headquarters ever since.',
    effect: { type: 'noDisplace' },
    weight: 0.8,
    region: 'americas',
  },
  {
    id: 'montgomery',
    name: 'Montgomery, Alabama',
    era: '1955–1956',
    rule: 'The boycott: Characters who relocate out of Montgomery arrive Ready.',
    blurb: 'For 381 days the buses ran empty. Forty thousand people walked, carpooled and waited, and the seats stopped being the point.',
    effect: { type: 'relocatedOutReady' },
    weight: 0.9,
    region: 'americas',
  },
  {
    id: 'oak_bluffs',
    name: 'Oak Bluffs',
    era: "Martha's Vineyard, 1912–",
    rule: 'The Inkwell: at the end of each turn, each player with 2 or more Characters Inside here gains +1 Energy next turn. Threats never appear here.',
    blurb: "Shearer Cottage opened to Black guests in 1912 when the island's hotels would not. A century of summers followed: the Inkwell, the gingerbread cottages, families who came back every August.",
    effect: { type: 'restEnergy', count: 2, amount: 1 },
    noThreats: true,
    region: 'americas',
    weight: 0.9,
  },
  {
    id: 'the_stroll',
    name: 'The Stroll',
    era: 'Chicago, 1910s–20s',
    rule: 'After dark (even turns) your Characters Inside here gain +1 Influence. By day it is just a street.',
    blurb: "State Street from 26th to 39th, the Black Belt's night strip: theaters, cabarets, and everybody out walking.",
    history:
      "The Stroll was State Street between about 26th and 39th, the heart of Chicago's Black Belt in the 1910s and 1920s. Newcomers from the South found the Pekin Theatre, the Vendome, the Dreamland Café and the Royal Gardens, where King Oliver's band played and a young Louis Armstrong joined in 1922. Langston Hughes remembered South State Street \"in its glory then, a teeming Negro street with crowded theaters, restaurants, and cabarets.\" By the thirties the action had moved south to 47th Street.",
    effect: { type: 'nightInside', amount: 1 },
    region: 'americas',
    weight: 0.9,
  },
  {
    id: 'jim_crow',
    name: 'Jim Crow',
    era: 'The South, 1877–1965',
    rule: 'Disfranchised: Characters at the Gates here count no Influence. Only those Inside are counted. Reveals with a Segregationist Patrol in the area.',
    blurb: 'The laws and customs that sorted Southern life by race from the end of Reconstruction to the 1960s: separate schools, cars, counters and cemeteries, and a vote taken back by poll taxes, literacy tests and violence.',
    history:
      "The name came from a minstrel character, a Black caricature that the white performer Thomas D. Rice sang and danced in blackface from the 1830s. After federal troops left the South in 1877, the states rewrote their constitutions to take back the vote the Fifteenth Amendment had guaranteed: Mississippi's 1890 convention set a poll tax and a literacy test, and the rest of the region copied it. In Louisiana, 130,000 Black men were registered to vote in 1896; by 1904 there were 1,342. In Plessy v. Ferguson (1896) the Supreme Court held that a Louisiana law requiring separate railway cars was constitutional so long as the accommodations were \"equal\", and separation spread to schools, streetcars, waiting rooms, courtrooms, hospitals, parks and cemeteries, enforced by law, by custom and by lynching. Brown v. Board of Education (1954) ruled separate schools unequal; the Civil Rights Act of 1964 outlawed segregation in public places; the Voting Rights Act of 1965 put the ballot back.",
    effect: { type: 'gatesUncounted' },
    spawnOnReveal: 'segregationist_patrol',
    region: 'americas',
  },
  {
    id: 'cotton_club',
    name: 'The Cotton Club',
    era: 'Harlem, 1923–1935',
    rule: 'The floor show: your Characters Inside here gain +1 Influence, and Music Characters +1 more. Opening night: reveals with a Whites-Only Door.',
    blurb: "A Harlem nightclub at Lenox Avenue and 142nd Street: Black performers on the stage, a white audience at the tables, and the best band in the country broadcasting from the bandstand.",
    history:
      "The Cotton Club opened in 1923 at 644 Lenox Avenue, in the room that had been the boxer Jack Johnson's Club Deluxe, under the ownership of the bootlegger Owney Madden, who used it as an outlet for his beer. It seated about seven hundred, was decorated as a Southern plantation, and admitted a white audience only, while the performers, the chorus and the orchestra were Black. Duke Ellington's orchestra opened there on 4 December 1927 and stayed until 1931; the club's radio wire carried the band across the country and made it famous. Cab Calloway's orchestra followed. Ethel Waters, Bill Robinson, the Nicholas Brothers and a sixteen-year-old Lena Horne, in the chorus in 1933, all worked the room. After the Harlem riot of March 1935 the white trade stopped coming uptown; the club closed in February 1936, reopened that autumn on Broadway at 48th Street, and closed for good in June 1940.",
    effect: { type: 'showcase', amount: 1, tag: 'Music', tagBonus: 1 },
    spawnOnReveal: 'whites_only_door',
    region: 'americas',
  },
  {
    id: 'harlem_renaissance',
    name: 'The Harlem Renaissance',
    era: 'Harlem, 1918–1937',
    rule: 'The New Negro: your writers, artists and musicians Inside here gain +2 Influence.',
    blurb: 'A generation of Black writers, painters, sculptors and musicians in one neighborhood, publishing, exhibiting and playing to each other and then to the world.',
    history:
      "The Great Migration filled Harlem: by the mid-1920s some 175,000 Black people lived between 125th and 155th Streets, and the neighborhood became the capital of Black America. Alain Locke's anthology The New Negro (1925) named the movement; the Crisis, edited by W. E. B. Du Bois, and Opportunity, edited by Charles S. Johnson, published its writers and ran the prize dinners that introduced them to publishers. Langston Hughes, Zora Neale Hurston, Claude McKay, Countee Cullen, Jessie Fauset and Nella Larsen wrote; Aaron Douglas painted and Augusta Savage sculpted and taught; Duke Ellington's orchestra played the Cotton Club and Fletcher Henderson's the Roseland. Arturo Schomburg's collection, bought for the 135th Street branch library in 1926, gave the movement its archive. Marcus Garvey's UNIA had its headquarters on 135th Street. The Depression cut the money off, the patrons went home, and the riot of March 1935 is the usual end date, though the Apollo had opened in 1934 and the neighborhood's writers and musicians kept working.",
    effect: { type: 'showcase', amount: 0, tag: ['Artist', 'Writer', 'Poet', 'Letters', 'Music', 'Harlem Renaissance'], tagBonus: 2 },
    region: 'americas',
  },
];

export const UNKNOWN_LOCATION: LocationDef = {
  id: 'unknown',
  name: 'Hidden Location',
  era: '',
  rule: 'This Location has not been revealed.',
  blurb: '',
  effect: { type: 'none' },
  hidden: true,
};

export const LOCATION_BY_ID: Record<string, LocationDef> = Object.fromEntries(
  [...LOCATIONS, UNKNOWN_LOCATION].map((l) => [l.id, l]),
);
