import { CHARACTERS, LOCATIONS, THREATS, EVENTS } from '../../engine';
import { abilityLines } from '../display';

export function RulesScreen({ onBack }: { onBack: () => void }) {
  return (
    <div className="screen" style={{ placeItems: 'start center' }}>
      <div className="inner rules">
        <button className="ghost" onClick={onBack} style={{ justifySelf: 'start' }}>
          ← Back
        </button>
        <h1 className="title">Rules</h1>
        <h2>The match</h2>
        <ul>
          <li>Two players, three Locations, seven turns (an 8th if someone Stands on Business), 13-card decks. Four-card opening hand and one draw every turn. Hands hold at most seven cards: a draw into a full hand is discarded.</li>
          <li>Both players plan at the same time, then <b>Lock It In</b>. Two minutes per turn.</li>
          <li>Win Influence at two of the three Locations to win the match.</li>
        </ul>
        <h2>Playing Characters</h2>
        <ul>
          <li>Every card has an <b>Energy</b> cost. Each turn you get Energy equal to the turn number (Turn 1: 1, Turn 5: 5); Hubert Harrison and Denmark Vesey add +1 while Established, Oak Bluffs pays +1 next turn, and unspent Energy does not carry over. Play as many cards as you can pay for and fit. A Character goes to one of your two Gate slots at a Location. Its <b>Reveal</b> ability triggers there.</li>
          <li><b>Discounts.</b> Some cards cost more than you will ever have on your own: Boukman Dutty is 7. Prices come down while a card waits in your hand. Booker T. Washington makes every Character 1 cheaper, Cécile Fatiman takes 2 off your most expensive card and 1 off every Rebellion Character, George Washington Carver knocks 1 off your priciest card at the end of each turn, and Boukman himself costs 1 less for each Rebellion Character you have on the board. A green cost on a card in your hand means it is discounted right now; a card never costs less than 0.</li>
          <li>Gate Characters count toward Influence but are <b>Fresh</b> for the turn they arrive and the following turn. Then they are <b>Ready</b> and may enter Inside (up to five per player).</li>
          <li>Inside, a Character is <b>Established</b>: its Established ability is live and it is safe from Gate-only effects.</li>
          <li><b>Straight Inside</b> and <b>Direct Entry</b> Characters can skip the wait (see Special arrivals below).</li>
        </ul>
        <h2>Hidden Locations</h2>
        <ul>
          <li>All three Locations start hidden. One reveals after each of the first three turns, in a random order. Turn 1 is a blind commitment.</li>
          <li>A Character committed blind is never rejected retroactively; it lives with whatever the Location turns out to be.</li>
        </ul>
        <h2>Influence and Force</h2>
        <ul>
          <li><b>Influence</b> decides who controls a Location. <b>Force</b> decides confrontations with Threats and challenges. They are deliberately separate.</li>
          <li>Ties at a Location count for nobody. If the match ends 1–1 with a tie, total Influence, then total Force, break the tie.</li>
          <li>Plan by dragging: a card onto a Location, a Ready Character into its Location, an Established Character to another Location, any Character onto a Threat. Tapping a card or tile opens the same actions. Drag a piece back to where it came from, or press Cmd/Ctrl+Z, to undo.</li>
        </ul>
        <h2>Movement</h2>
        <ul>
          <li><b>Day and night.</b> Odd turns are day, even turns are night. A <b>curfew</b> is a condition of a Location, not a Threat: at night nobody relocates out of Sundown Town until morning. Held Characters show a red Held strip. Only a curfew Location shows the time of day, since nothing else changes at night.</li>
          <li><b>Harriet Tubman</b> is the conductor: her Reveal moves one of your Characters, Gate or Inside, from anywhere straight Inside another Location, or to its Gates Ready if the Inside is full, even out of Sundown Town's curfew or The Justice System's hold. Free, and before anyone enters.</li>
          <li>Once per turn you may <b>Relocate</b> a Character to another Location's Gates. From Inside it arrives Fresh and waits again, unless an ability says otherwise. From the Gates it keeps its Ready status: a Ready Character waiting at the Gates is a flex piece you can commit late, wherever the fight turns out to be. The Inside is the committed zone; the Gates are the mobile one.</li>
          <li>Threats and abilities can <b>Displace</b> Characters against their will.</li>
        </ul>
        <h2>Threats</h2>
        <ul>
          <li>Threats are neutral dangers generated by Locations and by history moving on Turn 3. Tap a Threat to commit Characters' Force against it.</li>
          <li>Some Threats come one per player. Once yours is gone you may <b>Assist</b> against your opponent's, earning Solidarity (cosmetic only).</li>
          <li>A <b>Setback</b> is a loss suffered at the hands of injustice: a Threat or a hostile Location working against you. Your opponent's cards never cause one. <b>Reparations</b> converts Setbacks into Influence.</li>
          <li>Unresolved crises can make a Location <b>Lost</b>: nobody wins it.</li>
        </ul>
        <h2>Special arrivals</h2>
        <ul>
          <li><b>Straight Inside</b> (Sleeping Car Porters) always goes Inside the turn it is played. <b>Direct Entry</b> (Bessie Coleman) may: tap ⇅ on the planned move to choose Gates or Inside.</li>
          <li><b>The Ancestors</b> are never in a deck. In one match out of four, holding three Characters Inside at Accra, Ghana brings them to your hand. Play them while planning to see your opponent's plan for the turn and every danger the board is about to spring.</li>
          <li><b>The Tabernacle</b> protects your Characters from displacement. Establish Richard Allen, Absalom Jones and Daniel Payne there and <b>Black Jesus</b> appears: sanctuary at his Location and +1 Influence to every Character you control.</li>
          <li><b>The Justice System</b> holds anyone who goes Inside for two turns: no relocating out.</li>
          <li><b>Events</b> are played into the purple Event slot under a Location (one per Location per turn; the Gates can be full). They work everywhere and the Location adds a bonus: Reparations pays +1 more in the Americas, The Ancestors bless a Location in Africa, Word of Mouth draws two where you have a crowd, Community Defense adds Force where it lands, and <b>Persuade</b> (a <b>Curse</b>) drains every opposing Gate Character and turns the weakest one at its Location to your side at −1 Influence. Marie Laveau's Reveal takes the strongest. Some cards cost 0 Energy.</li>
          <li>Every deck carries at least one <b>Mythic</b>. The full list, with costs, is under <b>Cards</b> on the start screen.</li>
        </ul>
        <h2>Summon (cooperative)</h2>
        <ul>
          <li>Use quick chat (💬) to call <b>Summon?</b> at a Location with a Threat. If the other side answers <b>Summon!</b>, both of you commit that turn.</li>
          <li>Every Character of yours at that Location that is not moving adds its Force. If each player adds at least 1 and the total reaches 6, <b>Obatala</b> manifests: every Threat there dissolves, the Location can never be Lost, every Character there gains +1 Influence, and both players draw a card.</li>
          <li>If the Summon fails and that Location is later Lost, both players lose 1 Influence at each of their other Locations. A broken pact costs everyone.</li>
          <li>Mythic content is fantasy drawn from real traditions; the abilities are invention.</li>
        </ul>
        <h2>Legacy</h2>
        <ul>
          <li>Matches start at 1 Legacy. Either player may <b>Stand on Business</b> once to double it (1 → 2, then 2 → 4). Standing adds an <b>8th turn</b>, and whoever stood can no longer Sit Down.</li>
          <li>A Stand is part of your hidden plan and lands <b>one turn later</b>. The other player is never forced to answer: they get a full turn to <b>Sit Down</b> for the old Legacy, keep playing at the new Legacy, or <b>Stand back</b> and double it again.</li>
          <li><b>Sit Down</b> is surrender at the current Legacy. Sitting down during the grace turn is the cheap exit.</li>
        </ul>
        <h2>Resolution order</h2>
        <ol>
          <li>Location reveal</li>
          <li>New Characters placed, Events, then Reveal abilities (initiative order, alternating each turn)</li>
          <li>Voluntary Relocations</li>
          <li>Gate → Inside</li>
          <li>Confrontations, then Threat actions</li>
          <li>Cleanup: Fresh → Ready, Sundown Town, unstable Characters</li>
          <li>Influence update</li>
        </ol>
        {(['historical', 'archetype', 'mythic', 'gathering'] as const).map((cat) => (
          <div key={cat}>
            <h2>{cat === 'historical' ? 'Historical Characters' : cat === 'archetype' ? 'Archetypes' : cat === 'mythic' ? 'Mythic: African cosmology and diaspora spirituality' : 'Gatherings: they arrive on their own'}</h2>
            {cat === 'gathering' && <p className="muted">Gatherings are never in a deck. When the board earns one it appears with some fanfare and plays like any Character from then on. If a card ever returns one to your hand, you can replay it.</p>}
            {CHARACTERS.filter((c) => c.category === cat && !c.hidden).map((c) => (
              <div key={c.id} style={{ marginBottom: 8 }}>
                <b>{c.name}</b> <span className="muted">{c.influence} Influence · {c.force} Force · {c.era}</span>
                {abilityLines(c).map((l) => (
                  <div key={l.label} style={{ fontSize: 14 }}>
                    <span className="muted">{l.label}:</span> {l.text}
                  </div>
                ))}
              </div>
            ))}
          </div>
        ))}
        {false && CHARACTERS.map((c) => (
          <div key={c.id} style={{ marginBottom: 8 }}>
            <b>{c.name}</b> <span className="muted">{c.influence} Influence · {c.force} Force · {c.era}</span>
            {abilityLines(c).map((l) => (
              <div key={l.label} style={{ fontSize: 14 }}>
                <span className="muted">{l.label}:</span> {l.text}
              </div>
            ))}
          </div>
        ))}
        <h2>Events</h2>
        <p>An Event is dropped on a Location the same way a Character is: it goes into the purple Event slot beside your Gates, one per Location per turn, and the Gates can be full. Its effect reaches the whole board, and the Location it lands on adds a bonus, so where you play it is a real choice.</p>
        {EVENTS.map((e) => (
          <div key={e.id} style={{ marginBottom: 6 }}>
            <b>{e.name}</b>: {e.text}
          </div>
        ))}
        <h2>Locations</h2>
        {LOCATIONS.map((l) => (
          <div key={l.id} style={{ marginBottom: 6 }}>
            <b>{l.name}</b> <span className="muted">{l.era}</span>: {l.rule}
          </div>
        ))}
        <h2>Threats</h2>
        {THREATS.map((t) => (
          <div key={t.id} style={{ marginBottom: 6 }}>
            <b>{t.name}</b> <span className="muted">{t.family}</span>: {t.text}
          </div>
        ))}
        <button className="ghost" onClick={onBack} style={{ justifySelf: 'start' }}>
          ← Back
        </button>
      </div>
    </div>
  );
}
