import { CHARACTERS, LOCATIONS, THREATS, EVENTS } from '../../engine';
import { abilityLines } from '../display';

export function RulesScreen({ onBack }: { onBack: () => void }) {
  return (
    <div className="screen" style={{ placeItems: 'start center' }}>
      <div className="inner rules">
        <button className="ghost" onClick={onBack} style={{ justifySelf: 'start' }}>
          ← Back
        </button>
        <h1 className="title">Rules</h1>
        <h2>The match</h2>
        <ul>
          <li>Two players, three Locations, nine turns (ten if someone Stands on Business), 12-card decks. Four-card opening hand, draw one each turn until the deck runs out.</li>
          <li>Both players plan at the same time, then <b>Lock It In</b>. Two minutes per turn.</li>
          <li>Win Influence at two of the three Locations to win the match.</li>
        </ul>
        <h2>Playing Characters</h2>
        <ul>
          <li>One card per turn while any Location is hidden; <b>two</b> once all three are revealed. Organizer adds one more while Established. A Character goes to one of your two Gate slots at a Location. Its <b>Reveal</b> ability triggers there.</li>
          <li>Gate Characters count toward Influence but are <b>Fresh</b> for the turn they arrive and the following turn. Then they are <b>Ready</b> and may enter Inside (up to five per player).</li>
          <li>Inside, a Character is <b>Established</b>: its Established ability is live and it is safe from Gate-only effects.</li>
          <li><b>Direct Entry</b> Characters skip the wait.</li>
        </ul>
        <h2>Hidden Locations</h2>
        <ul>
          <li>All three Locations start hidden. One reveals after each of the first three turns, in a random order. Turn 1 is a blind commitment.</li>
          <li>A Character committed blind is never rejected retroactively; it lives with whatever the Location turns out to be.</li>
        </ul>
        <h2>Influence and Force</h2>
        <ul>
          <li><b>Influence</b> decides who controls a Location. <b>Force</b> decides confrontations with Threats and challenges. They are deliberately separate.</li>
          <li>Ties at a Location count for nobody. If the match ends 1–1 with a tie, total Influence, then total Force, break the tie.</li>
          <li>Plan by dragging: a card onto a Location, a Ready Character into its Location, an Established Character to another Location, any Character onto a Threat. Tapping a card or tile opens the same actions. Drag a piece back to where it came from, or press Cmd/Ctrl+Z, to undo.</li>
        </ul>
        <h2>Movement</h2>
        <ul>
          <li>Once per turn you may <b>Relocate</b> an Established Character to another Location's Gates. It arrives Fresh and waits again, unless an ability says otherwise.</li>
          <li>Threats and abilities can <b>Displace</b> Characters against their will.</li>
        </ul>
        <h2>Threats</h2>
        <ul>
          <li>Threats are neutral dangers generated by Locations and by history moving on Turn 3. Tap a Threat to commit Characters' Force against it.</li>
          <li>Some Threats come one per player. Once yours is gone you may <b>Assist</b> against your opponent's, earning Solidarity (cosmetic only).</li>
          <li>Harm caused by neutral Threats or hostile Locations counts as a <b>Setback</b>. <b>Reparations</b> converts Setbacks into Influence. The opponent's actions never count.</li>
          <li>Unresolved crises can make a Location <b>Lost</b>: nobody wins it.</li>
        </ul>
        <h2>Summon (cooperative)</h2>
        <ul>
          <li>Use quick chat (💬) to call <b>Summon?</b> at a Location with a Threat. If the other side answers <b>Summon!</b>, both of you commit that turn.</li>
          <li>Every Character of yours at that Location that is not moving adds its Force. If each player adds at least 1 and the total reaches 6, <b>Obatala</b> manifests: every Threat there dissolves, the Location can never be Lost, every Character there gains +1 Influence, and both players draw a card.</li>
          <li>If the Summon fails and that Location is later Lost, both players lose 1 Influence at each of their other Locations. A broken pact costs everyone.</li>
          <li>Mythic content is fantasy drawn from real traditions; the abilities are invention.</li>
        </ul>
        <h2>Stakes</h2>
        <ul>
          <li>Matches start at 1 Stake. Either player may <b>Stand on Business</b> once to double it (1 → 2, then 2 → 4). Standing extends the match to <b>ten turns</b>, and whoever stood can no longer Step Off.</li>
          <li>The other player must <b>Continue</b> or <b>Step Off</b>. Stepping off immediately loses the previously locked Stakes.</li>
          <li><b>Step Off</b> is surrender and is always available.</li>
        </ul>
        <h2>Resolution order</h2>
        <ol>
          <li>Location reveal</li>
          <li>New Characters placed, Events, then Reveal abilities (initiative order, alternating each turn)</li>
          <li>Voluntary Relocations</li>
          <li>Gate → Inside</li>
          <li>Confrontations, then Threat actions</li>
          <li>Cleanup: Fresh → Ready, Sundown Town, unstable Characters</li>
          <li>Influence update</li>
        </ol>
        {(['historical', 'archetype', 'mythic'] as const).map((cat) => (
          <div key={cat}>
            <h2>{cat === 'historical' ? 'Historical Characters' : cat === 'archetype' ? 'Archetypes' : 'Mythic: African cosmology and diaspora spirituality'}</h2>
            {CHARACTERS.filter((c) => c.category === cat).map((c) => (
              <div key={c.id} style={{ marginBottom: 8 }}>
                <b>{c.name}</b> <span className="muted">{c.influence} Influence · {c.force} Force · {c.era}</span>
                {abilityLines(c).map((l) => (
                  <div key={l.label} style={{ fontSize: 14 }}>
                    <span className="muted">{l.label}:</span> {l.text}
                  </div>
                ))}
              </div>
            ))}
          </div>
        ))}
        {false && CHARACTERS.map((c) => (
          <div key={c.id} style={{ marginBottom: 8 }}>
            <b>{c.name}</b> <span className="muted">{c.influence} Influence · {c.force} Force · {c.era}</span>
            {abilityLines(c).map((l) => (
              <div key={l.label} style={{ fontSize: 14 }}>
                <span className="muted">{l.label}:</span> {l.text}
              </div>
            ))}
          </div>
        ))}
        <h2>Events</h2>
        {EVENTS.map((e) => (
          <div key={e.id} style={{ marginBottom: 6 }}>
            <b>{e.name}</b>: {e.text}
          </div>
        ))}
        <h2>Locations</h2>
        {LOCATIONS.map((l) => (
          <div key={l.id} style={{ marginBottom: 6 }}>
            <b>{l.name}</b> <span className="muted">{l.era}</span>: {l.rule}
          </div>
        ))}
        <h2>Threats</h2>
        {THREATS.map((t) => (
          <div key={t.id} style={{ marginBottom: 6 }}>
            <b>{t.name}</b> <span className="muted">{t.family}</span>: {t.text}
          </div>
        ))}
        <button className="ghost" onClick={onBack} style={{ justifySelf: 'start' }}>
          ← Back
        </button>
      </div>
    </div>
  );
}
